#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright 2017-2022 F4PGA Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

"""The ``fasm`` package: parsing, formatting and merging FASM files.

This is the public API of the FPGA Assembly (FASM) Parser and Generation
library. It re-exports the model types from :mod:`fasm.model`
(:class:`~fasm.model.FasmLine`, :class:`~fasm.model.SetFasmFeature`,
:class:`~fasm.model.Annotation`, :class:`~fasm.model.ValueFormat`), the
parsing entry points from :mod:`fasm.parser`
(:func:`~fasm.parser.parse_fasm_filename`,
:func:`~fasm.parser.parse_fasm_string`), and the output/formatting
helpers below (:func:`fasm_line_to_string`, :func:`fasm_tuple_to_string`,
:func:`merge_features`, :func:`merge_and_sort`, ...). The default parser
implementation is a Rust extension module (``fasm._fasm_rs``, built from
``rust/fasm-python``); a pure Python ``textX`` based parser is always
installed as a fallback (see :mod:`fasm.parser`). See ``docs/PYTHON.md``
for a full API tour and ``docs/rewrite/COMPAT.md`` for any documented
behavioural difference from the original implementation.
"""

from __future__ import print_function

import os.path

from fasm.model import ValueFormat, SetFasmFeature, Annotation, FasmLine
from fasm.parser import parse_fasm_filename, parse_fasm_string

try:
    # Only used by fasm_tuple_to_string's fast path below (T3.3); importing
    # fasm.parser above already imported fasm._fasm_rs if it is available
    # (fasm.parser.rust does `from fasm import _fasm_rs`), so this rarely
    # does real work, but fasm._fasm_rs must stay importable on its own
    # (e.g. if fasm.parser.available doesn't include 'rust' for some other
    # reason).
    from fasm import _fasm_rs
except ImportError:
    _fasm_rs = None

try:
    from fasm.version import version_str
except ImportError:
    # fasm/version.py is only generated by update_version.py for the
    # legacy setup.py build (it is not tracked, and maturin never packages
    # it); the maturin built package has its version in the package
    # metadata.
    try:
        from importlib.metadata import version as _metadata_version
        version_str = _metadata_version('fasm')
    except Exception:
        version_str = "UNKNOWN"
__dir__ = os.path.split(os.path.abspath(os.path.realpath(__file__)))[0]
__version__ = version_str


# fasm_value_to_str, set_feature_width, set_feature_to_str,
# canonical_features and fasm_line_to_string stay pure Python (T3.3): they
# are called once per feature/line, each call is cheap (a handful of
# string operations), and fasm_tuple_to_string/fasm_line_to_string already
# have a whole-model Rust fast path above/in fasm/output.py that avoids the
# per-line Python call overhead for the common case (a list of FasmLine);
# a separate fast path for one line at a time would only help a caller
# that calls these directly per line, paying the Python<->Rust call
# overhead for work that is not the bottleneck. See
# docs/rewrite/DESIGN-python.md.
def fasm_value_to_str(value, width, value_format):
    """ Convert value from SetFasmFeature to a string. """
    if value_format == ValueFormat.PLAIN:
        return '{}'.format(value)
    elif value_format == ValueFormat.VERILOG_HEX:
        return "{}'h{:X}".format(width, value)
    elif value_format == ValueFormat.VERILOG_DECIMAL:
        return "{}'d{}".format(width, value)
    elif value_format == ValueFormat.VERILOG_OCTAL:
        return "{}'o{:o}".format(width, value)
    elif value_format == ValueFormat.VERILOG_BINARY:
        return "{}'b{:b}".format(width, value)
    else:
        assert False, value_format


def set_feature_width(set_feature):
    """ Return the bit width of a SetFasmFeature.

    `end - start + 1`, or 1 for a scalar (start/end-less) feature.
    """
    if set_feature.end is None:
        return 1
    else:
        assert set_feature.start is not None
        assert set_feature.start >= 0
        assert set_feature.end >= set_feature.start

        return set_feature.end - set_feature.start + 1


def set_feature_to_str(set_feature, check_if_canonical=False):
    """ Convert SetFasmFeature tuple to string. """
    feature_width = set_feature_width(set_feature)
    max_feature_value = 2**feature_width
    assert set_feature.value < max_feature_value

    if check_if_canonical:
        assert feature_width == 1
        assert set_feature.end is None
        if set_feature.start is not None:
            assert set_feature.start != 0
        assert set_feature.value_format is None

    feature = set_feature.feature
    address = ''
    feature_value = ''

    if set_feature.start is not None:
        if set_feature.end is not None:
            address = '[{}:{}]'.format(set_feature.end, set_feature.start)
        else:
            address = '[{}]'.format(set_feature.start)

    if set_feature.value_format is not None:
        feature_value = ' = {}'.format(
            fasm_value_to_str(
                value=set_feature.value,
                width=feature_width,
                value_format=set_feature.value_format))

    return '{}{}{}'.format(feature, address, feature_value)


def canonical_features(set_feature):
    """ Yield SetFasmFeature tuples that are of canonical form.

    EG width 1, and value 1.
    """
    if set_feature.value == 0:
        return

    if set_feature.start is None:
        assert set_feature.value == 1
        assert set_feature.end is None
        yield SetFasmFeature(
            feature=set_feature.feature,
            start=None,
            end=None,
            value=1,
            value_format=None,
        )

        return

    if set_feature.start is not None and set_feature.end is None:
        assert set_feature.value == 1

        if set_feature.start == 0:
            yield SetFasmFeature(
                feature=set_feature.feature,
                start=None,
                end=None,
                value=1,
                value_format=None,
            )
        else:
            yield SetFasmFeature(
                feature=set_feature.feature,
                start=set_feature.start,
                end=None,
                value=1,
                value_format=None,
            )

        return

    assert set_feature.start is not None
    assert set_feature.start >= 0
    assert set_feature.end >= set_feature.start

    for address in range(set_feature.start, set_feature.end + 1):
        value = (set_feature.value >> (address - set_feature.start)) & 1
        if value:
            if address == 0:
                yield SetFasmFeature(
                    feature=set_feature.feature,
                    start=None,
                    end=None,
                    value=1,
                    value_format=None,
                )
            else:
                yield SetFasmFeature(
                    feature=set_feature.feature,
                    start=address,
                    end=None,
                    value=1,
                    value_format=None,
                )


def fasm_line_to_string(fasm_line, canonical=False):
    """ Convert a single FasmLine tuple back to FASM text.

    Yields zero or more lines of text (a FasmLine with only a comment or
    only annotations still yields output; a completely empty line yields
    nothing). With ``canonical=True``, yields one line per canonical
    single-bit feature (see :func:`canonical_features`) and omits
    comments/annotations, matching ``fasm --canonical``.
    """
    if canonical:
        if fasm_line.set_feature:
            for feature in canonical_features(fasm_line.set_feature):
                yield set_feature_to_str(feature, check_if_canonical=True)

        return

    parts = []

    if fasm_line.set_feature:
        parts.append(set_feature_to_str(fasm_line.set_feature))

    if fasm_line.annotations and not canonical:
        annotations = '{{ {} }}'.format(
            ', '.join(
                '{} = "{}"'.format(annotation.name, annotation.value)
                for annotation in fasm_line.annotations))

        parts.append(annotations)

    if fasm_line.comment is not None and not canonical:
        comment = '#{}'.format(fasm_line.comment)
        parts.append(comment)

    if len(parts) == 0 and canonical:
        return

    yield ' '.join(parts)


def fasm_tuple_to_string(model, canonical=False):
    """ Returns string of FASM file for the model given.

    Note that calling parse_fasm_filename and then calling fasm_tuple_to_string
    will result in all optional whitespace replaced with one space.

    Uses fasm._fasm_rs.fasm_tuple_to_string (T3.3), a Rust implemented fast
    path, when the extension is available and it can reproduce this
    function's result exactly for ``model``; otherwise (extension not
    built, or ``model`` outside of what the fast path handles: see
    ``docs/rewrite/DESIGN-python.md``) falls back to the pure Python
    implementation below, which is also the reference: both give the same
    result, or the same exception, for every ``model``.
    """
    if _fasm_rs is not None:
        fast = _fasm_rs.fasm_tuple_to_string(model, canonical)
        if fast is not None:
            return fast

    lines = []
    for fasm_line in model:
        for line in fasm_line_to_string(fasm_line, canonical=canonical):
            lines.append(line)

    if canonical:
        lines = list(sorted(set(lines)))

    return '\n'.join(lines) + '\n'
