#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright 2017-2022 F4PGA Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
"""Tests for the T7.5 RapidWright cross-checks (tools/e2e/rapidwright/,
docs/rewrite/DESIGN-rapidwright.md).

Without any toolchain: the committed RapidWright layouts
(tests/corpus/{xilinx/*,prjuray/zynqusp}/rapidwright/*.json) are
consistent, and every RapidWright FASM design has its difftest.json,
README and reference frames.

With the Rust tools built (`cargo build --release`) and the pinned
databases fetched ($FASM_DB_CACHE): every part of every database walks
the same frame addresses (Rust writer + reader), has the same columns
(Rust walk and part.json), IDCODE and FDRI payload size as RapidWright's
layout of its device; the Rust `fasm2frames --sparse` gives the reference
frames of every RapidWright FASM design. With the prjuray-tools
ToolsTestData ($FASM_ORACLE_SRC): the xcku035 layout, and the prjxray
reader quirk RapidWright exposed (the last frame of a per frame CRC
bitstream is overwritten by the trailing pad frame) is kept.

With RapidWright (tools/e2e/setup-rapidwright.sh): `rwcheck.py --quick`
(layouts of three parts, eleven bitstream and .frm cases) has no
unexplained difference; with `--with-interchange` as well, the stored
FASM designs (RapidWright-built rings and two Vivado DCPs of RapidWright's
test data) are regenerated byte for byte and assemble identically with
the Rust and the reference `fasm2frames` (the reference needs
tests/oracle/setup-xilinx.sh, $FASM_ORACLE_DIR).
"""
import hashlib
import importlib.util
import json
import lzma
import os
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
RWCHECK_PATH = REPO_ROOT / 'tools' / 'e2e' / 'rapidwright' / 'rwcheck.py'
_spec = importlib.util.spec_from_file_location('rwcheck', RWCHECK_PATH)
rwcheck = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(rwcheck)

GOLDEN = sorted(
    (REPO_ROOT / 'tests' / 'corpus').glob('*/*/rapidwright/*.json'))
XILINX = REPO_ROOT / 'tests' / 'corpus' / 'xilinx'
FASM_DESIGNS = sorted(XILINX.glob('*/designs/rapidwright/*/*/rw.fasm'))


def _golden(path):
    return json.loads(path.read_text())


def _rust_built():
    return all(
        (rwcheck.RUST / t).is_file() for t in (
            'xc7frames2bit', 'bitread', 'xcframes2bit', 'uray-bitread',
            'fasm2frames'))


def _db_parts():
    return {p.name: p for p in rwcheck.db_parts()}


def test_golden_files_exist():
    assert len(GOLDEN) == 10, GOLDEN
    assert len(FASM_DESIGNS) == 5, FASM_DESIGNS


@pytest.mark.parametrize('path', GOLDEN, ids=lambda p: p.stem)
def test_golden_consistent(path):
    g = _golden(path)
    assert g['rapidwright'] == rwcheck.RW_TAG
    assert path.stem == g['device']
    assert g['parts'] and g['parts'] == sorted(g['parts'])
    assert all(p.startswith(g['device']) for p in g['parts'])
    assert g['words_per_frame'] == rwcheck.WORDS_PER_FRAME[g['series']]
    assert sum(c[1] for c in g['columns']) == g['walk_frames']
    fars = [int(c[0], 16) for c in g['columns']]
    assert len(set(fars)) == len(fars)
    minor = (1 << rwcheck.minor_bits(g['series'])) - 1
    assert all(f & minor == 0 for f in fars)
    # The FDRI payload: every frame and two pad frames per row.
    shift = 18 if g['series'] == 'UltraScalePlus' else 17
    rows = len({f >> shift for f in fars})
    assert g['config_array_words'] == g['words_per_frame'] * (
        g['walk_frames'] + g['frame_overhead_count_per_row'] * rows)


def _layout_cases():
    out = []
    for path in GOLDEN:
        for part in _golden(path)['parts']:
            out.append((path, part))
    return out


@pytest.mark.parametrize(
    'path,part',
    _layout_cases(),
    ids=lambda x: x if isinstance(x, str) else x.stem)
def test_rust_layout_equals_rapidwright(path, part, tmp_path):
    """The Rust part walk, part.json and FDRI size of every part equal
    RapidWright's layout of its device."""
    if not _rust_built():
        pytest.skip('Rust tools not built (cargo build --release)')
    if path.parent.parent.name == 'kintexu':
        parts = {p.name: p for p in rwcheck.extra_parts(tmp_path)}
    else:
        parts = _db_parts()
    if part not in parts:
        pytest.skip('part %s not fetched' % part)
    p = parts[part]
    g = _golden(path)
    walk, fdri = rwcheck.our_walk(p, tmp_path)
    assert rwcheck.compare_layout(p, g, walk, fdri) == []


@pytest.mark.parametrize(
    'fasm',
    FASM_DESIGNS,
    ids=lambda p: '%s/%s' % (p.parent.parent.name, p.parent.name))
def test_rapidwright_fasm_design(fasm, tmp_path):
    d = fasm.parent
    config = json.loads((d / 'difftest.json').read_text())
    readme = (d / 'README.md').read_text()
    data = fasm.read_bytes()
    assert hashlib.sha256(data).hexdigest() in readme
    ref = lzma.decompress((d / 'rw.sparse.frm.xz').read_bytes())
    assert hashlib.sha256(ref).hexdigest() in readme
    db = rwcheck.DB_CACHE / 'prjxray-db' / config['family'] / config['part']
    if not _rust_built() or not db.is_dir():
        pytest.skip('Rust tools or prjxray-db not available')
    out = tmp_path / 'rust.frm'
    rc, msg = rwcheck.fasm2frames(
        rwcheck.RUST / 'fasm2frames', config['family'], config['part'], fasm,
        out, True)
    assert rc == 0, msg
    assert out.read_bytes() == ref


def test_per_frame_crc_last_frame_quirk(tmp_path):
    """RapidWright showed that prjxray's reader loses the last frame of a
    per frame CRC bitstream: the pad frame after it is written over it.
    The Rust reader keeps that behaviour (COMPAT.md)."""
    ttd = rwcheck.tools_test_data(tmp_path)
    if ttd is None or not _rust_built():
        pytest.skip('ToolsTestData or the Rust tools not available')
    bit = ttd / 'Series7' / 'bram.bit'
    ours = rwcheck.our_read(
        'Series7', ttd / 'Series7' / 'part.yaml', bit, tmp_path / 'bram.frm')
    packets = rwcheck.fdri_packets(bit.read_bytes())
    per_frame, _ = rwcheck.packet_facts(bit.read_bytes())
    assert per_frame
    assert any(packets[-2]), 'the lost frame is not zero'
    assert not any(packets[-1])
    assert ours[max(ours)] == packets[-1]
    assert packets[-2] not in ours.values()


def _run_rwcheck(*args):
    env = dict(os.environ)
    with tempfile.TemporaryDirectory() as work:
        p = subprocess.run(
            [sys.executable,
             str(RWCHECK_PATH), '--work-dir', work] + list(args),
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=3600)
    return p.returncode, p.stdout.decode(errors='replace')


def test_rwcheck_quick():
    if not rwcheck.rapidwright_available():
        pytest.skip('RapidWright not set up (tools/e2e/setup-rapidwright.sh)')
    if not _rust_built() or not (rwcheck.DB_CACHE / 'prjxray-db').is_dir():
        pytest.skip('Rust tools or prjxray-db not available')
    rc, out = _run_rwcheck('--quick', 'layout', 'bits')
    assert rc == 0, out
    assert 'different' not in out, out


def test_rwcheck_fasm():
    if not rwcheck.rapidwright_available() or \
            not rwcheck.interchange_available():
        pytest.skip(
            'RapidWright interchange route not set up '
            '(setup-rapidwright.sh --with-interchange)')
    if not (rwcheck.ORACLE_DIR / 'venv-xilinx').is_dir():
        pytest.skip('reference fasm2frames not built ($FASM_ORACLE_DIR)')
    if not _rust_built():
        pytest.skip('Rust tools not built')
    rc, out = _run_rwcheck('fasm')
    assert rc == 0, out
    # 3 RapidWright-built designs, 4 Vivado DCPs whose FASM both
    # fasm2frames accept (2) or reject with the same errors (2); 6 cases
    # the route cannot handle (docs/rewrite/DESIGN-rapidwright.md).
    assert 'fasm: 13 cases: identical 7, not possible 6' in out, out
    assert 'different' not in out, out
