// Copyright 2017-2022 F4PGA Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

//! C ABI wrapper for the `fasm` crate.
//!
//! This crate will build `libfasm` (cdylib + staticlib) with a C ABI for
//! parsing (callback + array APIs), formatting and canonicalisation, with
//! a header generated by cbindgen at `include/fasm/fasm.h` and a header
//! only C++ RAII wrapper at `include/fasm/fasm.hpp` (see task T4.1 and
//! `docs/rewrite/PLAN.md`).
//!
//! No C ABI functions exist yet; this crate currently only depends on the
//! `fasm` core crate for the workspace skeleton (task T0.3).

#[cfg(test)]
mod tests {
    #[test]
    fn depends_on_fasm_crate() {
        assert!(!fasm::VERSION.is_empty());
    }
}
