/*
 * libfasm: C API of the Rust FASM (FPGA Assembly) library.
 *
 * See docs/rewrite/DESIGN-capi.md for ownership, lifetime, error and
 * thread safety rules. In short:
 *  - objects returned by fasm_*_new, fasm_parse_*, *_to_string,
 *    fasm_set_feature_name_string and fasm_file_merge_and_sort* are owned
 *    by the caller and released with the matching fasm_*_free function;
 *  - pointers returned by accessors borrow from their parent object;
 *  - fallible functions report details through an optional
 *    `fasm_error **err` argument (free with fasm_error_free);
 *  - borrowed strings (fasm_str) are NOT NUL terminated, owned strings
 *    (fasm_string) are.
 */

#ifndef FASM_FASM_H
#define FASM_FASM_H

/*
 * Generated by cbindgen from rust/fasm-capi/src (configuration:
 * rust/fasm-capi/cbindgen.toml). Do not edit: regenerate with
 * `make capi-header`.
 *
 * Copyright 2017-2022 F4PGA Authors
 * SPDX-License-Identifier: Apache-2.0
 */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
/*
 * FASM_API marks the exported functions. On Windows, define FASM_STATIC
 * when linking the static library; otherwise the functions are imported
 * from the DLL. Elsewhere it gives them default visibility.
 */
#ifndef FASM_API
#  if defined(_WIN32) || defined(__CYGWIN__)
#    if defined(FASM_STATIC)
#      define FASM_API
#    else
#      define FASM_API __declspec(dllimport)
#    endif
#  elif defined(__GNUC__) && __GNUC__ >= 4
#    define FASM_API __attribute__((visibility("default")))
#  else
#    define FASM_API
#  endif
#endif


/**
 * Result code of a fallible function.
 *
 * Values are stable (part of the ABI); new codes may be added at the end.
 */
typedef enum fasm_status {
    /**
     * Success.
     */
    FASM_OK = 0,
    /**
     * The FASM text does not match the grammar or its values do not fit
     * (`fasm_error_line` / `fasm_error_column` locate the error).
     */
    FASM_ERR_PARSE = 1,
    /**
     * A file could not be read.
     */
    FASM_ERR_IO = 2,
    /**
     * An argument is invalid: a `NULL` pointer where an object is
     * required, an out of range value, an invalid `SetFasmFeature` (end
     * without start, value too wide for its address, ...).
     */
    FASM_ERR_INVALID_ARG = 3,
    /**
     * Text that must be UTF-8 is not (in an argument, or a comment /
     * annotation value of parsed FASM text).
     */
    FASM_ERR_UTF8 = 4,
    /**
     * An internal error (a Rust panic caught at the C boundary). Please
     * report it as a bug.
     */
    FASM_ERR_PANIC = 5,
    /**
     * Formatting or merging a model failed (for example conflicting bits
     * in `fasm_file_merge_and_sort`).
     */
    FASM_ERR_OUTPUT = 6,
} fasm_status;

/**
 * How the value of a `SetFasmFeature` is written (Python:
 * `fasm.ValueFormat`, whose values 0 to 4 are kept), or
 * `FASM_VALUE_FORMAT_NONE` when no value was written (`FEATURE` or
 * `FEATURE[3]`, an implicit 1; Python: `value_format is None`).
 */
typedef enum fasm_value_format {
    /**
     * No value written (implicit 1).
     */
    FASM_VALUE_FORMAT_NONE = -1,
    /**
     * A plain decimal number, e.g. `42`.
     */
    FASM_VALUE_FORMAT_PLAIN = 0,
    /**
     * A Verilog decimal number, e.g. `8'd42`.
     */
    FASM_VALUE_FORMAT_VERILOG_DECIMAL = 1,
    /**
     * A Verilog hexadecimal number, e.g. `8'h2A`.
     */
    FASM_VALUE_FORMAT_VERILOG_HEX = 2,
    /**
     * A Verilog binary number, e.g. `8'b00101010`.
     */
    FASM_VALUE_FORMAT_VERILOG_BINARY = 3,
    /**
     * A Verilog octal number, e.g. `8'o52`.
     */
    FASM_VALUE_FORMAT_VERILOG_OCTAL = 4,
} fasm_value_format;

/**
 * Details of a failed call: status, message and (for parse errors) the
 * position in the input.
 *
 * Created by fallible functions in their `fasm_error **err` argument,
 * owned by the caller and released with `fasm_error_free`. Immutable, so
 * it can be read from any thread.
 */
typedef struct fasm_error fasm_error;

/**
 * A FASM model: an ordered list of lines (Python: the list returned by
 * `fasm.parse_fasm_string`).
 *
 * Created by `fasm_parse_string`, `fasm_parse_file`, `fasm_file_new` and
 * `fasm_file_merge_and_sort*`; owned by the caller and released with
 * `fasm_file_free`. Reading a `fasm_file` from several threads at once is
 * safe; modifying it (`fasm_file_push_line`) requires exclusive access.
 */
typedef struct fasm_file fasm_file;

/**
 * One line of a FASM model (Python: `fasm.FasmLine`): an optional
 * `SetFasmFeature`, optional annotations and an optional comment.
 *
 * Always borrowed: from a `fasm_file` (`fasm_file_line`, valid until the
 * file is freed or modified), or passed to a `fasm_line_callback` (valid
 * only during the callback).
 */
typedef struct fasm_line fasm_line;

/**
 * The `SetFasmFeature` of a line (Python: `fasm.SetFasmFeature`): a
 * feature name, an optional `[end:start]` address, a value and the
 * format the value was written in.
 *
 * Always borrowed from its `fasm_line` (`fasm_line_set_feature`) and
 * valid as long as that line is.
 */
typedef struct fasm_set_feature fasm_set_feature;

/**
 * An owned, immutable UTF-8 string returned by the library.
 *
 * Its text is NUL terminated (`fasm_string_data`) and its length is
 * known (`fasm_string_len`); the text itself may contain NUL bytes (for
 * example from a comment), in which case only the length is reliable.
 * Owned by the caller and released with `fasm_string_free`.
 */
typedef struct fasm_string fasm_string;

/**
 * A borrowed string view: `len` bytes of UTF-8 text starting at `ptr`.
 *
 * **Not NUL terminated.** When filled in by the library (comments,
 * annotations), it points into the owning object (a `fasm_file`, or the
 * line passed to a streaming callback) and is valid as long as that object
 * is; for an empty string `ptr` may point to a zero length buffer (never
 * `NULL` when filled in by the library). When passed to the library,
 * `ptr` may be `NULL` only if `len` is 0; the bytes must be valid UTF-8.
 */
typedef struct fasm_str {
    /**
     * First byte of the text.
     */
    const char *ptr;
    /**
     * Length of the text in bytes (not counting any terminator).
     */
    size_t len;
} fasm_str;

/**
 * Input description of a `SetFasmFeature` for `fasm_file_push_line`.
 *
 * All pointers are only read during the call (the library copies what it
 * keeps).
 */
typedef struct fasm_set_feature_spec {
    /**
     * The feature name (UTF-8, e.g. `CLBLL_L_X12Y124.SLICEL_X0.BLUT.INIT`).
     * Like the Python model, the name is not checked against the FASM
     * grammar.
     */
    struct fasm_str feature;
    /**
     * Whether `start` is given (`FEATURE[start]` or `FEATURE[end:start]`).
     */
    bool has_start;
    /**
     * Start (low) address bit; ignored unless `has_start`.
     */
    uint32_t start;
    /**
     * Whether `end` is given (`FEATURE[end:start]`; requires `has_start`).
     */
    bool has_end;
    /**
     * End (high) address bit; ignored unless `has_end`.
     */
    uint32_t end;
    /**
     * The value as `value_len` little endian bytes (any length; `NULL`
     * with `value_len == 0` is the value 0).
     */
    const uint8_t *value_le;
    /**
     * Number of bytes at `value_le`.
     */
    size_t value_len;
    /**
     * One of the `fasm_value_format` values (`FASM_VALUE_FORMAT_NONE` for
     * no written value, which is printed as the bare feature name and
     * normally goes with the value 1). An `int32_t` so that any value can
     * be checked.
     */
    int32_t value_format;
} fasm_set_feature_spec;

/**
 * One `name = "value"` annotation of a line, as two borrowed strings
 * (not NUL terminated). The value is the raw text between the quotes:
 * escapes such as `\"` are not decoded.
 */
typedef struct fasm_annotation {
    /**
     * The annotation name.
     */
    struct fasm_str name;
    /**
     * The annotation value (possibly empty).
     */
    struct fasm_str value;
} fasm_annotation;

/**
 * Callback deciding whether a feature is a "zero" feature for
 * `fasm_file_merge_and_sort_ex` (Python: `zero_function`).
 *
 * `feature` is the feature name (NUL terminated, `len` bytes, valid only
 * during the call); `user` is the `user` pointer given to
 * `fasm_file_merge_and_sort_ex`. Must not unwind or `longjmp`.
 */
typedef bool (*fasm_zero_fn)(const char *feature, size_t len, void *user);

/**
 * Callback computing the sort key of a feature group for
 * `fasm_file_merge_and_sort_ex` (Python: `sort_key`).
 *
 * `group_id` is the group id (the first `.` separated component of the
 * feature names, e.g. the tile name; NUL terminated, `len` bytes, valid
 * only during the call). Groups are sorted by increasing key, groups with
 * equal keys by `group_id`. May be called several times per group. Must
 * not unwind or `longjmp`.
 */
typedef int64_t (*fasm_sort_key_fn)(const char *group_id, size_t len, void *user);

/**
 * Callback of the streaming parsers (`fasm_parse_string_cb`,
 * `fasm_parse_file_cb`), called once per FASM line in file order.
 *
 * * `line`: the parsed line, valid **only during the call** (copy out
 *   what you need to keep).
 * * `line_number`: the 1 based line number where the FASM line starts
 *   (lines are counted at `\n`, like `fasm_error_line`).
 * * `user`: the `user` pointer given to the parse function.
 *
 * Return `true` to continue, `false` to stop parsing (the parse function
 * then returns `FASM_OK` without looking at the rest of the input). The
 * callback must not unwind (throw a C++ exception) or `longjmp` out.
 */
typedef bool (*fasm_line_callback)(const struct fasm_line *line, size_t line_number, void *user);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the library version as a static NUL terminated string (never
 * `NULL`, never freed), e.g. `"0.1.0"`.
 */
FASM_API const char *fasm_version(void);

/**
 * Creates a new, empty `fasm_file` (free with `fasm_file_free`). Never
 * returns `NULL` (except on memory exhaustion, which aborts).
 */
FASM_API struct fasm_file *fasm_file_new(void);

/**
 * Appends a line to `file` (Python: appending a `fasm.FasmLine` to a
 * model).
 *
 * * `set_feature`: the `SetFasmFeature`, or `NULL` for none. Validated
 *   like `fasm.SetFasmFeature`: end without start, end before start and
 *   a value wider than the address are `FASM_ERR_INVALID_ARG`.
 * * `annotations[0..annotation_count]`: the annotations (`NULL` with a
 *   count of 0 for none). Names and values are copied verbatim.
 * * `comment`: the comment text after `#`, or `NULL` for no comment (a
 *   non-`NULL` empty string is a bare `#`).
 *
 * All strings must be UTF-8 (else `FASM_ERR_UTF8`). On any error nothing
 * is appended. Appending invalidates the `fasm_line` (and
 * `fasm_set_feature`, `fasm_str`) pointers previously obtained from
 * `file`.
 *
 * # Safety
 *
 * `file` must be `NULL` or a live `fasm_file` not accessed concurrently;
 * `set_feature` and `comment` must be `NULL` or readable (with the
 * strings they point to); `annotations` must be `NULL` or valid for
 * reading `annotation_count` entries; `err` must be `NULL` or writable.
 */
FASM_API
enum fasm_status fasm_file_push_line(struct fasm_file *file,
                                     const struct fasm_set_feature_spec *set_feature,
                                     const struct fasm_annotation *annotations,
                                     size_t annotation_count,
                                     const struct fasm_str *comment,
                                     struct fasm_error **err);

/**
 * Returns the status code of `error`.
 *
 * Returns `FASM_ERR_INVALID_ARG` for a `NULL` `error`.
 *
 * # Safety
 *
 * `error` must be `NULL` or a live `fasm_error` from this library.
 */
FASM_API enum fasm_status fasm_error_status(const struct fasm_error *error);

/**
 * Returns the message of `error`: NUL terminated UTF-8, owned by `error`
 * (valid until `fasm_error_free`).
 *
 * For parse errors it has the form `Parse error at LINE:COLUMN - ...`.
 * Returns an empty string for a `NULL` `error`.
 *
 * # Safety
 *
 * `error` must be `NULL` or a live `fasm_error` from this library.
 */
FASM_API const char *fasm_error_message(const struct fasm_error *error);

/**
 * Returns the 1 based line of a parse error (lines are counted at `\n`),
 * or 0 when the error has no position (not a parse error, or `NULL`).
 *
 * # Safety
 *
 * `error` must be `NULL` or a live `fasm_error` from this library.
 */
FASM_API size_t fasm_error_line(const struct fasm_error *error);

/**
 * Returns the 0 based column (in Unicode code points) of a parse error,
 * or 0 when the error has no position (not a parse error, or `NULL`).
 *
 * # Safety
 *
 * `error` must be `NULL` or a live `fasm_error` from this library.
 */
FASM_API size_t fasm_error_column(const struct fasm_error *error);

/**
 * Frees `error`. `NULL` is accepted (no-op).
 *
 * # Safety
 *
 * `error` must be `NULL` or a live `fasm_error` from this library that is
 * not used afterwards (in particular not freed twice).
 */
FASM_API void fasm_error_free(struct fasm_error *error);

/**
 * Returns a short static description of the status code `status` (NUL
 * terminated, never `NULL`, never freed), e.g. `"parse error"` for
 * `FASM_ERR_PARSE`, or `"unknown status"` for a value that is not a
 * `fasm_status`.
 *
 * Takes an `int` rather than a `fasm_status` so that any integer can be
 * passed safely.
 */
FASM_API const char *fasm_status_string(int status);

/**
 * Returns the number of lines in `file` (0 for a `NULL` `file`).
 *
 * # Safety
 *
 * `file` must be `NULL` or a live `fasm_file` from this library.
 */
FASM_API size_t fasm_file_line_count(const struct fasm_file *file);

/**
 * Returns line `index` (0 based) of `file`, or `NULL` if `file` is `NULL`
 * or `index >= fasm_file_line_count(file)`.
 *
 * The line is borrowed from `file`: it stays valid until `file` is freed
 * or modified (`fasm_file_push_line`).
 *
 * # Safety
 *
 * `file` must be `NULL` or a live `fasm_file` from this library.
 */
FASM_API const struct fasm_line *fasm_file_line(const struct fasm_file *file, size_t index);

/**
 * Frees `file` and everything borrowed from it (lines, set features,
 * strings). `NULL` is accepted (no-op).
 *
 * # Safety
 *
 * `file` must be `NULL` or a live `fasm_file` from this library that is
 * not used afterwards (in particular not freed twice).
 */
FASM_API void fasm_file_free(struct fasm_file *file);

/**
 * Groups and sorts the lines of `file` into a new `fasm_file` (Python:
 * `fasm.output.merge_and_sort(model)` without `zero_function` and
 * `sort_key`), leaving `file` unchanged.
 *
 * Features are grouped by their first name component (the tile) and
 * groups sorted by name; runs of comment lines and annotation lines stay
 * attached to the following feature; address only features of one name
 * are merged into a single multi bit feature where possible; groups are
 * separated by a blank line. Returns `NULL` on error (`FASM_ERR_OUTPUT`
 * when features cannot be merged, `FASM_ERR_INVALID_ARG` for a `NULL`
 * `file`). Free the result with `fasm_file_free`.
 *
 * # Safety
 *
 * `file` must be `NULL` or a live `fasm_file`; `err` must be `NULL` or
 * writable.
 */
FASM_API
struct fasm_file *fasm_file_merge_and_sort(const struct fasm_file *file,
                                           struct fasm_error **err);

/**
 * `fasm_file_merge_and_sort` with the optional Python callbacks:
 * `zero_fn` (a feature group whose features all answer `true` is
 * dropped) and `sort_key_fn` (group sort key; see `fasm_sort_key_fn`).
 * Either may be `NULL`. `user` is passed to both.
 *
 * # Safety
 *
 * `file` must be `NULL` or a live `fasm_file`; the callbacks must be
 * `NULL` or functions that can be called with `user`; `err` must be
 * `NULL` or writable.
 */
FASM_API
struct fasm_file *fasm_file_merge_and_sort_ex(const struct fasm_file *file,
                                              fasm_zero_fn zero_fn,
                                              fasm_sort_key_fn sort_key_fn,
                                              void *user,
                                              struct fasm_error **err);

/**
 * Returns `true` if `line` has a `SetFasmFeature` (`false` for `NULL`).
 *
 * # Safety
 *
 * `line` must be `NULL` or a valid `fasm_line` (see `fasm_line`).
 */
FASM_API bool fasm_line_has_set_feature(const struct fasm_line *line);

/**
 * Returns the `SetFasmFeature` of `line`, borrowed from `line`, or `NULL`
 * if it has none (or `line` is `NULL`).
 *
 * # Safety
 *
 * `line` must be `NULL` or a valid `fasm_line` (see `fasm_line`).
 */
FASM_API const struct fasm_set_feature *fasm_line_set_feature(const struct fasm_line *line);

/**
 * Returns the number of annotations of `line` (0 when it has no
 * `{ ... }` block, or `line` is `NULL`).
 *
 * # Safety
 *
 * `line` must be `NULL` or a valid `fasm_line` (see `fasm_line`).
 */
FASM_API size_t fasm_line_annotation_count(const struct fasm_line *line);

/**
 * Stores annotation `index` (0 based, in file order) of `line` in `*out`
 * and returns `true`; the strings are borrowed from `line`.
 *
 * Returns `false` (leaving `*out` unchanged) if `line` or `out` is `NULL`
 * or `index >= fasm_line_annotation_count(line)`.
 *
 * # Safety
 *
 * `line` must be `NULL` or a valid `fasm_line`; `out` must be `NULL` or
 * writable.
 */
FASM_API
bool fasm_line_annotation(const struct fasm_line *line,
                          size_t index,
                          struct fasm_annotation *out);

/**
 * Returns `true` if `line` has a comment (`#`, possibly with empty text).
 * `false` for `NULL`.
 *
 * # Safety
 *
 * `line` must be `NULL` or a valid `fasm_line` (see `fasm_line`).
 */
FASM_API bool fasm_line_has_comment(const struct fasm_line *line);

/**
 * Stores the comment text of `line` (everything after `#`, verbatim,
 * borrowed from `line`, not NUL terminated) in `*out` and returns
 * `true`.
 *
 * Returns `false` and stores an empty view (`NULL`, 0) if `line` has no
 * comment or is `NULL`; `out` may be `NULL` to only test for a comment.
 *
 * # Safety
 *
 * `line` must be `NULL` or a valid `fasm_line`; `out` must be `NULL` or
 * writable.
 */
FASM_API bool fasm_line_comment(const struct fasm_line *line, struct fasm_str *out);

/**
 * Returns the length in bytes of the feature name of `sf` (0 for
 * `NULL`).
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`.
 */
FASM_API size_t fasm_set_feature_name_len(const struct fasm_set_feature *sf);

/**
 * Copies the feature name of `sf` into `buf` with `snprintf` semantics
 * and returns its full length in bytes (not counting the NUL).
 *
 * Feature names are stored interned and split at `.`, so there is no
 * contiguous string to borrow; this copies without allocating. If
 * `buf_len > 0`, at most `buf_len - 1` bytes are copied and a NUL is
 * appended; the name was truncated if the return value is `>= buf_len`.
 * `buf` may be `NULL` when `buf_len` is 0 (to query the length). Returns 0
 * for a `NULL` `sf` (and stores an empty string if `buf_len > 0`).
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`; `buf` must be valid
 * for writing `buf_len` bytes (or `NULL` with `buf_len == 0`).
 */
FASM_API size_t fasm_set_feature_name(const struct fasm_set_feature *sf, char *buf, size_t buf_len);

/**
 * Returns the feature name of `sf` as a new `fasm_string` (free with
 * `fasm_string_free`), or `NULL` if `sf` is `NULL`.
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`.
 */
FASM_API struct fasm_string *fasm_set_feature_name_string(const struct fasm_set_feature *sf);

/**
 * Returns `true` if `sf` has a `FeatureAddress` (`FEATURE[start]` or
 * `FEATURE[end:start]`). `false` for `NULL`.
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`.
 */
FASM_API bool fasm_set_feature_has_start(const struct fasm_set_feature *sf);

/**
 * Returns the start (low) bit of the address of `sf`, or 0 if it has no
 * address (check `fasm_set_feature_has_start`) or `sf` is `NULL`.
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`.
 */
FASM_API uint32_t fasm_set_feature_start(const struct fasm_set_feature *sf);

/**
 * Returns `true` if `sf` has an end (high) bit (`FEATURE[end:start]`).
 * `false` for `NULL`.
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`.
 */
FASM_API bool fasm_set_feature_has_end(const struct fasm_set_feature *sf);

/**
 * Returns the end (high) bit of the address of `sf`, or 0 if it has none
 * (check `fasm_set_feature_has_end`) or `sf` is `NULL`.
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`.
 */
FASM_API uint32_t fasm_set_feature_end(const struct fasm_set_feature *sf);

/**
 * Returns the format the value of `sf` was written in, or
 * `FASM_VALUE_FORMAT_NONE` if no value was written (or `sf` is `NULL`).
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`.
 */
FASM_API enum fasm_value_format fasm_set_feature_value_format(const struct fasm_set_feature *sf);

/**
 * Returns the width in bits of the address of `sf`: 1 without an address
 * or with a single bit address, `end - start + 1` for a range (Python:
 * `fasm.set_feature_width`). 0 for `NULL`.
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`.
 */
FASM_API uint32_t fasm_set_feature_width(const struct fasm_set_feature *sf);

/**
 * Returns the number of bits needed to hold the value of `sf`: 0 for the
 * value 0, otherwise one more than the index of its highest set bit. 0
 * for `NULL`.
 *
 * Values have no size limit (a 256 bit BRAM `INIT` value is common); use
 * `fasm_set_feature_value_bytes_le` or `fasm_set_feature_value_bit` for
 * values wider than 64 bits.
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`.
 */
FASM_API uint32_t fasm_set_feature_value_bits(const struct fasm_set_feature *sf);

/**
 * Stores the value of `sf` in `*out` and returns `true` if it fits in 64
 * bits; returns `false` (leaving `*out` unchanged) if it does not, or
 * `sf` or `out` is `NULL`.
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`; `out` must be `NULL`
 * or writable.
 */
FASM_API bool fasm_set_feature_value_u64(const struct fasm_set_feature *sf, uint64_t *out);

/**
 * Returns bit `index` of the value of `sf` (bit 0 is the least
 * significant); `false` beyond `fasm_set_feature_value_bits` and for
 * `NULL`.
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`.
 */
FASM_API bool fasm_set_feature_value_bit(const struct fasm_set_feature *sf, uint32_t index);

/**
 * Copies the value of `sf` into `buf` as a little endian byte string and
 * returns the number of bytes the value needs: `(value_bits + 7) / 8`, so
 * 0 for the value 0 (and for `NULL`).
 *
 * If `buf_len` is at least the returned size, the value is written to
 * `buf[0..size]` and the rest of `buf[0..buf_len]` is zero filled (so a
 * 32 byte buffer receives any value of up to 256 bits, zero extended).
 * Otherwise `buf` is not touched: call again with a large enough buffer.
 * `buf` may be `NULL` when `buf_len` is 0 (to query the size).
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`; `buf` must be valid
 * for writing `buf_len` bytes (or `NULL` with `buf_len == 0`).
 */
FASM_API
size_t fasm_set_feature_value_bytes_le(const struct fasm_set_feature *sf,
                                       uint8_t *buf,
                                       size_t buf_len);

/**
 * Returns the value of `sf` as digits in `radix` (2, 8, 10 or 16), with no
 * prefix or width and without leading zeros (`"0"` for 0), hex digits in
 * upper case if `uppercase`. Free with `fasm_string_free`.
 *
 * Returns `NULL` (and sets `*err` to a `FASM_ERR_INVALID_ARG` error) if
 * `sf` is `NULL` or `radix` is not supported.
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`; `err` must be `NULL`
 * or writable.
 */
FASM_API
struct fasm_string *fasm_set_feature_value_to_string(const struct fasm_set_feature *sf,
                                                     uint32_t radix,
                                                     bool uppercase,
                                                     struct fasm_error **err);

/**
 * Renders all lines of `file` as FASM text (Python:
 * `fasm.fasm_tuple_to_string(model, canonical)`): one line per
 * `fasm_line`, each ending in `\n` (an empty file gives `"\n"`), with
 * optional whitespace normalised to single spaces.
 *
 * With `canonical`, every set feature is expanded to one line per set
 * bit (`FEATURE[bit]`, or `FEATURE` for bit 0 of a feature without
 * address), cleared bits, annotations and comments are dropped, and the
 * lines are sorted and deduplicated.
 *
 * Returns a new `fasm_string` (free with `fasm_string_free`), or `NULL`
 * on error (`FASM_ERR_INVALID_ARG` for a `NULL` `file`, `FASM_ERR_OUTPUT`
 * if a feature cannot be formatted).
 *
 * # Safety
 *
 * `file` must be `NULL` or a live `fasm_file`; `err` must be `NULL` or
 * writable.
 */
FASM_API
struct fasm_string *fasm_file_to_string(const struct fasm_file *file,
                                        bool canonical,
                                        struct fasm_error **err);

/**
 * Renders one line (Python: `fasm.fasm_line_to_string`, whose list of
 * strings is joined with `\n` here, without a trailing `\n`).
 *
 * Without `canonical` this is exactly one line of text (possibly empty,
 * for a blank line). With `canonical` it is the canonical lines of the
 * line's set feature (none, i.e. an empty string, for a line without one
 * or with the value 0), in bit order and not deduplicated.
 *
 * Returns a new `fasm_string`, or `NULL` on error (as
 * `fasm_file_to_string`).
 *
 * # Safety
 *
 * `line` must be `NULL` or a valid `fasm_line`; `err` must be `NULL` or
 * writable.
 */
FASM_API
struct fasm_string *fasm_line_to_string(const struct fasm_line *line,
                                        bool canonical,
                                        struct fasm_error **err);

/**
 * Renders a set feature (Python: `fasm.set_feature_to_str(set_feature,
 * check_if_canonical)`), e.g. `A.B[7:0] = 8'hFF`.
 *
 * With `check_if_canonical`, a feature that is not in canonical form
 * (wider than one bit, with an end address, a start address of 0 or a
 * written value) is `FASM_ERR_OUTPUT`.
 *
 * Returns a new `fasm_string`, or `NULL` on error.
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`; `err` must be `NULL`
 * or writable.
 */
FASM_API
struct fasm_string *fasm_set_feature_to_string(const struct fasm_set_feature *sf,
                                               bool check_if_canonical,
                                               struct fasm_error **err);

/**
 * Parses the FASM text `text[0..len]` (UTF-8, need not be NUL terminated)
 * into a new `fasm_file`, stored in `*out` (Python:
 * `fasm.parse_fasm_string`).
 *
 * A UTF-8 byte order mark at the start is skipped. Invalid UTF-8 in a
 * comment or annotation value is `FASM_ERR_UTF8`; any other invalid input
 * is `FASM_ERR_PARSE`. On failure `*out` is set to `NULL` and, if `err` is
 * not `NULL`, `*err` receives the error (with `fasm_error_line` /
 * `fasm_error_column`); on success `*out` owns the new file (free with
 * `fasm_file_free`) and `*err` is set to `NULL`.
 *
 * Returns `FASM_ERR_INVALID_ARG` if `out` is `NULL`, or `text` is `NULL`
 * with a non-zero `len`.
 *
 * # Safety
 *
 * `text` must be `NULL` (with `len == 0`) or valid for reading `len`
 * bytes; `out` must be `NULL` or writable; `err` must be `NULL` or
 * writable.
 */
FASM_API
enum fasm_status fasm_parse_string(const char *text,
                                   size_t len,
                                   struct fasm_file **out,
                                   struct fasm_error **err);

/**
 * Reads and parses the FASM file `path` (NUL terminated; any bytes on
 * Unix, UTF-8 on other systems) into a new `fasm_file`, stored in `*out`
 * (Python: `fasm.parse_fasm_filename`).
 *
 * A file that cannot be read is `FASM_ERR_IO` (line and column 0);
 * otherwise as `fasm_parse_string`.
 *
 * # Safety
 *
 * `path` must be `NULL` or a NUL terminated string; `out` and `err` must
 * be `NULL` or writable.
 */
FASM_API
enum fasm_status fasm_parse_file(const char *path,
                                 struct fasm_file **out,
                                 struct fasm_error **err);

/**
 * Parses the FASM text `text[0..len]` like `fasm_parse_string`, but
 * instead of building a `fasm_file` calls `callback` for each line (see
 * `fasm_line_callback`), which avoids holding the whole model in memory.
 *
 * Lines before a parse error are passed to `callback`; the error is then
 * returned (`FASM_ERR_PARSE` / `FASM_ERR_UTF8`, with `*err` set). Returns
 * `FASM_OK` when the whole input was parsed or `callback` returned
 * `false`, and `FASM_ERR_INVALID_ARG` for a `NULL` `callback`, or a
 * `NULL` `text` with a non-zero `len`.
 *
 * # Safety
 *
 * `text` must be `NULL` (with `len == 0`) or valid for reading `len`
 * bytes; `callback` must be `NULL` or a function that can be called with
 * `user`; `err` must be `NULL` or writable.
 */
FASM_API
enum fasm_status fasm_parse_string_cb(const char *text,
                                      size_t len,
                                      fasm_line_callback callback,
                                      void *user,
                                      struct fasm_error **err);

/**
 * Reads the FASM file `path` (see `fasm_parse_file`) and streams its
 * lines to `callback` (see `fasm_parse_string_cb`).
 *
 * # Safety
 *
 * `path` must be `NULL` or a NUL terminated string; `callback` must be
 * `NULL` or a function that can be called with `user`; `err` must be
 * `NULL` or writable.
 */
FASM_API
enum fasm_status fasm_parse_file_cb(const char *path,
                                    fasm_line_callback callback,
                                    void *user,
                                    struct fasm_error **err);

/**
 * Returns the NUL terminated text of `s`, owned by `s` (valid until
 * `fasm_string_free`). Returns an empty string for a `NULL` `s`.
 *
 * # Safety
 *
 * `s` must be `NULL` or a live `fasm_string` from this library.
 */
FASM_API const char *fasm_string_data(const struct fasm_string *s);

/**
 * Returns the length of `s` in bytes, not counting the NUL terminator (0
 * for a `NULL` `s`).
 *
 * # Safety
 *
 * `s` must be `NULL` or a live `fasm_string` from this library.
 */
FASM_API size_t fasm_string_len(const struct fasm_string *s);

/**
 * Frees `s`. `NULL` is accepted (no-op).
 *
 * # Safety
 *
 * `s` must be `NULL` or a live `fasm_string` from this library that is not
 * used afterwards (in particular not freed twice).
 */
FASM_API void fasm_string_free(struct fasm_string *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* FASM_FASM_H */
