/*
 * libfasm_capi: C API of the Rust FASM (FPGA Assembly) library.
 *
 * See docs/rewrite/DESIGN-capi.md for ownership, lifetime, error and
 * thread safety rules. In short:
 *  - objects returned by fasm_*_new, fasm_parse_*, *_to_string,
 *    fasm_set_feature_name_string and fasm_file_merge_and_sort* are owned
 *    by the caller and released with the matching fasm_*_free function;
 *  - pointers returned by accessors borrow from their parent object;
 *  - fallible functions report details through an optional
 *    `fasm_error **err` argument (free with fasm_error_free);
 *  - borrowed strings (fasm_str) are NOT NUL terminated, owned strings
 *    (fasm_string) are.
 */

#ifndef FASM_FASM_H
#define FASM_FASM_H

/*
 * Generated by cbindgen from rust/fasm-capi/src (configuration:
 * rust/fasm-capi/cbindgen.toml). Do not edit: regenerate with
 * `make capi-header`.
 *
 * Copyright 2017-2022 F4PGA Authors
 * SPDX-License-Identifier: Apache-2.0
 */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
/*
 * FASM_API marks the exported functions. On Windows, define FASM_STATIC
 * when linking the static library; otherwise the functions are imported
 * from the DLL. Elsewhere it gives them default visibility.
 */
#ifndef FASM_API
#  if defined(_WIN32) || defined(__CYGWIN__)
#    if defined(FASM_STATIC)
#      define FASM_API
#    else
#      define FASM_API __declspec(dllimport)
#    endif
#  elif defined(__GNUC__) && __GNUC__ >= 4
#    define FASM_API __attribute__((visibility("default")))
#  else
#    define FASM_API
#  endif
#endif


/**
 * Result code of a fallible function.
 *
 * Values are stable (part of the ABI); new codes may be added at the end.
 */
typedef enum fasm_status {
    /**
     * Success.
     */
    FASM_OK = 0,
    /**
     * The FASM text does not match the grammar or its values do not fit
     * (`fasm_error_line` / `fasm_error_column` locate the error).
     */
    FASM_ERR_PARSE = 1,
    /**
     * A file could not be read.
     */
    FASM_ERR_IO = 2,
    /**
     * An argument is invalid: a `NULL` pointer where an object is
     * required, an out of range value, an invalid `SetFasmFeature` (end
     * without start, value too wide for its address, ...).
     */
    FASM_ERR_INVALID_ARG = 3,
    /**
     * Text that must be UTF-8 is not (in an argument, or a comment /
     * annotation value of parsed FASM text).
     */
    FASM_ERR_UTF8 = 4,
    /**
     * An internal error (a Rust panic caught at the C boundary). Please
     * report it as a bug.
     */
    FASM_ERR_PANIC = 5,
    /**
     * Formatting or merging a model failed (for example conflicting bits
     * in `fasm_file_merge_and_sort`).
     */
    FASM_ERR_OUTPUT = 6,
    /**
     * A Xilinx database cannot be opened: a missing or malformed file, an
     * unknown part, not a prjxray-db / prjuray-db family directory, a
     * part file that cannot be used, a part without a frame tree
     * (`fasm_xilinx_*`).
     */
    FASM_ERR_DB = 7,
    /**
     * FASM features that are not in the database
     * (`prjxray.fasm_assembler.FasmLookupError`; the message has one line
     * per missing feature bit).
     */
    FASM_ERR_LOOKUP = 8,
    /**
     * Two FASM lines want a different value for one bit
     * (`prjxray.fasm_assembler.FasmInconsistentBits`).
     */
    FASM_ERR_INCONSISTENT_BITS = 9,
    /**
     * Any other error of the Xilinx assembler: an unknown tile or tile type
     * (`KeyError`), a malformed ROI `design.json`, ... (`fasm_error_kind`
     * names the exception of the reference tools).
     */
    FASM_ERR_ASSEMBLER = 10,
    /**
     * A bitstream cannot be written or read: a part of another
     * architecture than the format's, frames of another size, data
     * without a sync word, an IDCODE that is not the part's.
     */
    FASM_ERR_BITSTREAM = 11,
    /**
     * A number of a `.frm` file does not parse.
     */
    FASM_ERR_FRM = 12,
} fasm_status;

/**
 * How the value of a `SetFasmFeature` is written (Python:
 * `fasm.ValueFormat`, whose values 0 to 4 are kept), or
 * `FASM_VALUE_FORMAT_NONE` when no value was written (`FEATURE` or
 * `FEATURE[3]`, an implicit 1; Python: `value_format is None`).
 */
typedef enum fasm_value_format {
    /**
     * No value written (implicit 1).
     */
    FASM_VALUE_FORMAT_NONE = -1,
    /**
     * A plain decimal number, e.g. `42`.
     */
    FASM_VALUE_FORMAT_PLAIN = 0,
    /**
     * A Verilog decimal number, e.g. `8'd42`.
     */
    FASM_VALUE_FORMAT_VERILOG_DECIMAL = 1,
    /**
     * A Verilog hexadecimal number, e.g. `8'h2A`.
     */
    FASM_VALUE_FORMAT_VERILOG_HEX = 2,
    /**
     * A Verilog binary number, e.g. `8'b00101010`.
     */
    FASM_VALUE_FORMAT_VERILOG_BINARY = 3,
    /**
     * A Verilog octal number, e.g. `8'o52`.
     */
    FASM_VALUE_FORMAT_VERILOG_OCTAL = 4,
} fasm_value_format;

/**
 * The architecture of a Xilinx database or part.
 *
 * Values are stable (part of the ABI).
 */
typedef enum fasm_xilinx_architecture {
    /**
     * 7 series (prjxray-db: artix7, kintex7, spartan7, zynq7).
     */
    FASM_XILINX_SERIES7 = 0,
    /**
     * UltraScale.
     */
    FASM_XILINX_ULTRASCALE = 1,
    /**
     * UltraScale+ (prjuray-db: zynqusp).
     */
    FASM_XILINX_ULTRASCALE_PLUS = 2,
} fasm_xilinx_architecture;

/**
 * The layout of a bitstream (`fasm_xilinx_bitstream_options.format`).
 *
 * Values are stable (part of the ABI).
 */
typedef enum fasm_xilinx_bitstream_format {
    /**
     * The part's architecture (prjuray-tools' implementation, which is
     * prjxray's for Series7).
     */
    FASM_XILINX_FORMAT_DEFAULT = 0,
    /**
     * Series7 (`xc7frames2bit`).
     */
    FASM_XILINX_FORMAT_SERIES7 = 1,
    /**
     * UltraScale (`xcframes2bit --architecture=UltraScale`).
     */
    FASM_XILINX_FORMAT_ULTRASCALE = 2,
    /**
     * UltraScale+ (`xcframes2bit --architecture=UltraScalePlus`).
     */
    FASM_XILINX_FORMAT_ULTRASCALE_PLUS = 3,
    /**
     * The plain prjxray `xc7frames2bit --architecture=UltraScale`: the
     * Series7 part type, frame addresses and ECC with the UltraScale word
     * count and packets.
     */
    FASM_XILINX_FORMAT_PRJXRAY_ULTRASCALE = 4,
    /**
     * The plain prjxray `xc7frames2bit --architecture=UltraScalePlus`.
     */
    FASM_XILINX_FORMAT_PRJXRAY_ULTRASCALE_PLUS = 5,
} fasm_xilinx_bitstream_format;

/**
 * An owned, immutable byte buffer returned by the library (a bitstream).
 * Released with `fasm_bytes_free`.
 */
typedef struct fasm_bytes fasm_bytes;

/**
 * Details of a failed call: status, message and (for parse errors) the
 * position in the input.
 *
 * Created by fallible functions in their `fasm_error **err` argument,
 * owned by the caller and released with `fasm_error_free`. Immutable, so
 * it can be read from any thread.
 */
typedef struct fasm_error fasm_error;

/**
 * A FASM model: an ordered list of lines (Python: the list returned by
 * `fasm.parse_fasm_string`).
 *
 * Created by `fasm_parse_string`, `fasm_parse_file`, `fasm_file_new` and
 * `fasm_file_merge_and_sort*`; owned by the caller and released with
 * `fasm_file_free`. Reading a `fasm_file` from several threads at once is
 * safe; modifying it (`fasm_file_push_line`) requires exclusive access.
 */
typedef struct fasm_file fasm_file;

/**
 * One line of a FASM model (Python: `fasm.FasmLine`): an optional
 * `SetFasmFeature`, optional annotations and an optional comment.
 *
 * Always borrowed: from a `fasm_file` (`fasm_file_line`, valid until the
 * file is freed or modified), or passed to a `fasm_line_callback` (valid
 * only during the callback).
 */
typedef struct fasm_line fasm_line;

/**
 * The `SetFasmFeature` of a line (Python: `fasm.SetFasmFeature`): a
 * feature name, an optional `[end:start]` address, a value and the
 * format the value was written in.
 *
 * Always borrowed from its `fasm_line` (`fasm_line_set_feature`) and
 * valid as long as that line is.
 */
typedef struct fasm_set_feature fasm_set_feature;

/**
 * An owned, immutable UTF-8 string returned by the library.
 *
 * Its text is NUL terminated (`fasm_string_data`) and its length is
 * known (`fasm_string_len`); the text itself may contain NUL bytes (for
 * example from a comment), in which case only the length is reliable.
 * Owned by the caller and released with `fasm_string_free`.
 */
typedef struct fasm_string fasm_string;

/**
 * A FASM -> frames assembler (Python: `fasm.xilinx.FasmAssembler`, a
 * port of `prjxray.fasm_assembler.FasmAssembler`).
 *
 * Created by `fasm_xilinx_assembler_new` for a database opened with a
 * part, released with `fasm_xilinx_assembler_free`. It shares the
 * ownership of its database. A call that modifies it needs exclusive
 * access (one thread at a time).
 */
typedef struct fasm_xilinx_assembler fasm_xilinx_assembler;

/**
 * A prjxray-db (Series7) or prjuray-db (UltraScale+) database family
 * opened for one part (Python: `fasm.xilinx.Database`).
 *
 * Created by `fasm_xilinx_database_open` / `_open_cached`, released with
 * `fasm_xilinx_database_free`. Immutable: any number of threads may use
 * it at once. Assemblers and parts made from it share its ownership, so
 * it may be freed before them.
 */
typedef struct fasm_xilinx_database fasm_xilinx_database;

/**
 * Configuration frames: frame address -> `words_per_frame` 32-bit
 * words, in ascending address order (Python: `fasm.xilinx.Frames`).
 *
 * Created by `fasm_xilinx_frames_new`, `fasm_xilinx_assembler_get_frames`,
 * `fasm_xilinx_fasm2frames_*`, `fasm_xilinx_frames_read_frm` /
 * `_parse_frm` and `fasm_xilinx_bitstream_read*`; released with
 * `fasm_xilinx_frames_free`. Reading from several threads at once is
 * safe; `fasm_xilinx_frames_set` needs exclusive access.
 */
typedef struct fasm_xilinx_frames fasm_xilinx_frames;

/**
 * The frame tree and IDCODE of a part (`part.yaml`), which a bitstream is
 * written for and read with.
 *
 * Created by `fasm_xilinx_part_from_database` or
 * `fasm_xilinx_part_read_yaml`, released with `fasm_xilinx_part_free`.
 * Immutable: any number of threads may use it at once.
 */
typedef struct fasm_xilinx_part fasm_xilinx_part;

/**
 * A borrowed string view: `len` bytes of UTF-8 text starting at `ptr`.
 *
 * **Not NUL terminated.** When filled in by the library (comments,
 * annotations), it points into the owning object (a `fasm_file`, or the
 * line passed to a streaming callback) and is valid as long as that object
 * is. When `len` is 0, `ptr` must not be dereferenced: it can be any
 * value, including `NULL` (the empty view `fasm_line_comment` stores for a
 * line without comment). When passed to the library, `ptr` may be `NULL`
 * only if `len` is 0; the bytes must be valid UTF-8.
 */
typedef struct fasm_str {
    /**
     * First byte of the text.
     */
    const char *ptr;
    /**
     * Length of the text in bytes (not counting any terminator).
     */
    size_t len;
} fasm_str;

/**
 * Input description of a `SetFasmFeature` for `fasm_file_push_line`.
 *
 * All pointers are only read during the call (the library copies what it
 * keeps).
 */
typedef struct fasm_set_feature_spec {
    /**
     * The feature name (UTF-8, e.g. `CLBLL_L_X12Y124.SLICEL_X0.BLUT.INIT`).
     * Like the Python model, the name is not checked against the FASM
     * grammar.
     */
    struct fasm_str feature;
    /**
     * Whether `start` is given (`FEATURE[start]` or `FEATURE[end:start]`).
     */
    bool has_start;
    /**
     * Start (low) address bit; ignored unless `has_start`.
     */
    uint32_t start;
    /**
     * Whether `end` is given (`FEATURE[end:start]`; requires `has_start`).
     */
    bool has_end;
    /**
     * End (high) address bit; ignored unless `has_end`.
     */
    uint32_t end;
    /**
     * The value as `value_len` little endian bytes (any length; `NULL`
     * with `value_len == 0` is the value 0).
     */
    const uint8_t *value_le;
    /**
     * Number of bytes at `value_le`.
     */
    size_t value_len;
    /**
     * One of the `fasm_value_format` values (`FASM_VALUE_FORMAT_NONE` for
     * no written value, which is printed as the bare feature name and
     * normally goes with the value 1). An `int32_t` so that any value can
     * be checked.
     */
    int32_t value_format;
} fasm_set_feature_spec;

/**
 * One `name = "value"` annotation of a line, as two borrowed strings
 * (not NUL terminated). The value is the raw text between the quotes:
 * escapes such as `\"` are not decoded.
 */
typedef struct fasm_annotation {
    /**
     * The annotation name.
     */
    struct fasm_str name;
    /**
     * The annotation value (possibly empty).
     */
    struct fasm_str value;
} fasm_annotation;

/**
 * Callback deciding whether a feature is a "zero" feature for
 * `fasm_file_merge_and_sort_ex` (Python: `zero_function`).
 *
 * `feature` is the feature name (NUL terminated, `len` bytes, valid only
 * during the call); `user` is the `user` pointer given to
 * `fasm_file_merge_and_sort_ex`. Must not unwind (throw)
 * or `longjmp` out: that is undefined behaviour.
 */
typedef bool (*fasm_zero_fn)(const char *feature, size_t len, void *user);

/**
 * Callback computing the sort key of a feature group for
 * `fasm_file_merge_and_sort_ex` (Python: `sort_key`).
 *
 * `group_id` is the group id (the first `.` separated component of the
 * feature names, e.g. the tile name; NUL terminated, `len` bytes, valid
 * only during the call). It is called exactly once per group (the result
 * is cached), so it need not be deterministic. Groups are sorted by
 * increasing key, groups with equal keys by `group_id`. Must not unwind
 * (throw) or `longjmp` out: that is undefined behaviour.
 */
typedef int64_t (*fasm_sort_key_fn)(const char *group_id, size_t len, void *user);

/**
 * Callback of the streaming parsers (`fasm_parse_string_cb`,
 * `fasm_parse_file_cb`), called once per FASM line in file order.
 *
 * * `line`: the parsed line, valid **only during the call** (copy out
 *   what you need to keep).
 * * `line_number`: the 1 based line number where the FASM line starts
 *   (lines are counted at `\n`, like `fasm_error_line`).
 * * `user`: the `user` pointer given to the parse function.
 *
 * Return `true` to continue, `false` to stop parsing (the parse function
 * then returns `FASM_OK` without looking at the rest of the input). The
 * callback must not unwind (throw a C++ exception) or `longjmp` out:
 * that is undefined behaviour.
 */
typedef bool (*fasm_line_callback)(const struct fasm_line *line, size_t line_number, void *user);

/**
 * A callback receiving a warning of the reference tools (for example
 * `frame_set: invalid word address ...`, which prjxray prints to stderr):
 * `len` bytes of UTF-8 at `message` (also NUL terminated), valid during
 * the call. It must not unwind (throw a C++ exception) or `longjmp` out.
 */
typedef void (*fasm_xilinx_warning_fn)(const char *message, size_t len, void *user);

/**
 * The options of `fasm_xilinx_fasm2frames_*` (the flags of the
 * `fasm2frames` tool). A `NULL` options pointer is all defaults (zero).
 */
typedef struct fasm_xilinx_fasm2frames_options {
    /**
     * `--sparse`: only the frames of the buses that were written (and of
     * the ROI tiles) instead of every frame of the part.
     */
    bool sparse;
    /**
     * `--emit_pudc_b_pullup`: make the PUDC_B pin an input with a pullup
     * if the FASM does not use its IOB.
     */
    bool emit_pudc_b_pullup;
    /**
     * `--roi`: a ROI `design.json` (NUL terminated path), or `NULL`.
     */
    const char *roi;
    /**
     * Receives the warnings (bits beyond the end of a frame), or `NULL`.
     */
    fasm_xilinx_warning_fn warning;
    /**
     * Passed to `warning`.
     */
    void *user;
} fasm_xilinx_fasm2frames_options;

/**
 * The options of the bitstream writer. A `NULL` options pointer is all
 * defaults (zero).
 */
typedef struct fasm_xilinx_bitstream_options {
    /**
     * A `fasm_xilinx_bitstream_format` value.
     */
    int32_t format;
    /**
     * The header part name (field b), NUL terminated; `NULL`: the part of
     * the database for a part from `fasm_xilinx_part_from_database`, else
     * empty.
     */
    const char *part_name;
    /**
     * The header design name (field a, before `;Generator=`;
     * `xc7frames2bit` writes its `--frm_file`), NUL terminated; `NULL`:
     * empty.
     */
    const char *design_name;
    /**
     * The generator name after `;Generator=`, NUL terminated; `NULL`:
     * `xc7frames2bit`.
     */
    const char *generator;
    /**
     * Use `source_date_epoch` for the header date and time.
     */
    bool has_source_date_epoch;
    /**
     * Seconds since the epoch of the header date and time (UTC). Without
     * `has_source_date_epoch`, `$SOURCE_DATE_EPOCH` when it is set to an
     * integer (like the command line tools), else the current time.
     */
    int64_t source_date_epoch;
} fasm_xilinx_bitstream_options;

/**
 * What a feature bit is (`fasm_xilinx_database_lookup`).
 */
typedef struct fasm_xilinx_feature_info {
    /**
     * `true` for a pseudo PIP: valid, sets no bits (the other fields are
     * 0, `block_type` is -1).
     */
    bool pseudo_pip;
    /**
     * The bus: 0 `CLB_IO_CLK`, 1 `BLOCK_RAM`, 2 `CFG_CLB`; -1 for a
     * pseudo PIP.
     */
    int32_t block_type;
    /**
     * The first frame of the bus of the tile.
     */
    uint32_t base_address;
    /**
     * The number of frames of the bus of the tile.
     */
    uint32_t frame_count;
    /**
     * The effective word offset of the tile in its frames.
     */
    int64_t offset;
    /**
     * The number of bits (the ones that cannot be placed in a frame,
     * which the assembler drops with a warning, are not counted).
     */
    size_t bit_count;
} fasm_xilinx_feature_info;

/**
 * A bit a feature sets or clears (`fasm_xilinx_database_lookup`).
 */
typedef struct fasm_xilinx_bit {
    /**
     * Frame address.
     */
    uint32_t frame;
    /**
     * 32-bit word within the frame.
     */
    uint32_t word;
    /**
     * Bit within the word (0 to 31).
     */
    uint32_t bit;
    /**
     * `true` if the feature sets the bit, `false` if it clears it (a `!`
     * segbit).
     */
    bool value;
} fasm_xilinx_bit;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the library version as a static NUL terminated string (never
 * `NULL`, never freed), e.g. `"0.1.0"`.
 */
FASM_API const char *fasm_version(void);

/**
 * Creates a new, empty `fasm_file` (free with `fasm_file_free`). Never
 * returns `NULL` (except on memory exhaustion, which aborts).
 */
FASM_API struct fasm_file *fasm_file_new(void);

/**
 * Appends a line to `file` (Python: appending a `fasm.FasmLine` to a
 * model).
 *
 * * `set_feature`: the `SetFasmFeature`, or `NULL` for none. Validated
 *   like `fasm.SetFasmFeature`: end without start, end before start and
 *   a value wider than the address are `FASM_ERR_INVALID_ARG`.
 * * `annotations[0..annotation_count]`: the annotations (`NULL` with a
 *   count of 0 for none). Names and values are copied verbatim.
 * * `comment`: the comment text after `#`, or `NULL` for no comment (a
 *   non-`NULL` empty string is a bare `#`).
 *
 * All strings must be UTF-8 (else `FASM_ERR_UTF8`). On any error nothing
 * is appended. Appending invalidates the `fasm_line` (and
 * `fasm_set_feature`, `fasm_str`) pointers previously obtained from
 * `file`.
 *
 * # Safety
 *
 * `file` must be `NULL` or a live `fasm_file` not accessed concurrently;
 * `set_feature` and `comment` must be `NULL` or readable (with the
 * strings they point to); `annotations` must be `NULL` or valid for
 * reading `annotation_count` entries; `err` must be `NULL` or writable.
 */
FASM_API
enum fasm_status fasm_file_push_line(struct fasm_file *file,
                                     const struct fasm_set_feature_spec *set_feature,
                                     const struct fasm_annotation *annotations,
                                     size_t annotation_count,
                                     const struct fasm_str *comment,
                                     struct fasm_error **err);

/**
 * Returns the status code of `error`.
 *
 * Returns `FASM_ERR_INVALID_ARG` for a `NULL` `error`.
 *
 * # Safety
 *
 * `error` must be `NULL` or a live `fasm_error` from this library.
 */
FASM_API enum fasm_status fasm_error_status(const struct fasm_error *error);

/**
 * Returns the message of `error`: NUL terminated UTF-8, owned by `error`
 * (valid until `fasm_error_free`).
 *
 * For parse errors it has the form `Parse error at LINE:COLUMN - ...`.
 * Returns an empty string for a `NULL` `error`.
 *
 * # Safety
 *
 * `error` must be `NULL` or a live `fasm_error` from this library.
 */
FASM_API const char *fasm_error_message(const struct fasm_error *error);

/**
 * Returns the 1 based line of a parse error (lines are counted at `\n`),
 * or 0 when the error has no position (not a parse error, or `NULL`).
 *
 * # Safety
 *
 * `error` must be `NULL` or a live `fasm_error` from this library.
 */
FASM_API size_t fasm_error_line(const struct fasm_error *error);

/**
 * Returns the 0 based column (in Unicode code points) of a parse error,
 * or 0 when the error has no position (not a parse error, or `NULL`).
 *
 * # Safety
 *
 * `error` must be `NULL` or a live `fasm_error` from this library.
 */
FASM_API size_t fasm_error_column(const struct fasm_error *error);

/**
 * Returns the kind of `error`: for the errors of the `fasm_xilinx_*`
 * functions, the name of the exception the reference Python tools
 * (prjxray, f4pga-xc-fasm) raise in the same situation, which the
 * command line tools print before the message
 * (`prjxray.fasm_assembler.FasmLookupError`, `KeyError`,
 * `FileNotFoundError`, `Exception` for a parse error, ...); for other
 * errors, `fasm_status_string` of its status. NUL terminated, owned by
 * `error` (valid until `fasm_error_free`); an empty string for a `NULL`
 * `error`.
 *
 * # Safety
 *
 * `error` must be `NULL` or a live `fasm_error` from this library.
 */
FASM_API const char *fasm_error_kind(const struct fasm_error *error);

/**
 * Frees `error`. `NULL` is accepted (no-op).
 *
 * # Safety
 *
 * `error` must be `NULL` or a live `fasm_error` from this library that is
 * not used afterwards (in particular not freed twice).
 */
FASM_API void fasm_error_free(struct fasm_error *error);

/**
 * Returns a short static description of the status code `status` (NUL
 * terminated, never `NULL`, never freed), e.g. `"parse error"` for
 * `FASM_ERR_PARSE`, or `"unknown status"` for a value that is not a
 * `fasm_status`.
 *
 * Takes an `int` rather than a `fasm_status` so that any integer can be
 * passed safely.
 */
FASM_API const char *fasm_status_string(int status);

/**
 * Returns the number of lines in `file` (0 for a `NULL` `file`).
 *
 * # Safety
 *
 * `file` must be `NULL` or a live `fasm_file` from this library.
 */
FASM_API size_t fasm_file_line_count(const struct fasm_file *file);

/**
 * Returns line `index` (0 based) of `file`, or `NULL` if `file` is `NULL`
 * or `index >= fasm_file_line_count(file)`.
 *
 * The line is borrowed from `file`: it stays valid until `file` is freed
 * or modified (`fasm_file_push_line`).
 *
 * # Safety
 *
 * `file` must be `NULL` or a live `fasm_file` from this library.
 */
FASM_API const struct fasm_line *fasm_file_line(const struct fasm_file *file, size_t index);

/**
 * Frees `file` and everything borrowed from it (lines, set features,
 * strings). `NULL` is accepted (no-op).
 *
 * # Safety
 *
 * `file` must be `NULL` or a live `fasm_file` from this library that is
 * not used afterwards (in particular not freed twice).
 */
FASM_API void fasm_file_free(struct fasm_file *file);

/**
 * Groups and sorts the lines of `file` into a new `fasm_file` (Python:
 * `fasm.output.merge_and_sort(model)` without `zero_function` and
 * `sort_key`), leaving `file` unchanged.
 *
 * Features are grouped by their first name component (the tile) and
 * groups sorted by name; runs of comment lines and annotation lines stay
 * attached to the following feature; address only features of one name
 * are merged into a single multi bit feature where possible; groups are
 * separated by a blank line. Returns `NULL` on error (`FASM_ERR_OUTPUT`
 * when features cannot be merged, `FASM_ERR_INVALID_ARG` for a `NULL`
 * `file`). Free the result with `fasm_file_free`.
 *
 * # Safety
 *
 * `file` must be `NULL` or a live `fasm_file`; `err` must be `NULL` or
 * writable.
 */
FASM_API
struct fasm_file *fasm_file_merge_and_sort(const struct fasm_file *file,
                                           struct fasm_error **err);

/**
 * `fasm_file_merge_and_sort` with the optional Python callbacks:
 * `zero_fn` (a feature group whose features all answer `true` is
 * dropped) and `sort_key_fn` (group sort key; see `fasm_sort_key_fn`).
 * Either may be `NULL`. `user` is passed to both.
 *
 * # Safety
 *
 * `file` must be `NULL` or a live `fasm_file`; the callbacks must be
 * `NULL` or functions that can be called with `user`; `err` must be
 * `NULL` or writable.
 */
FASM_API
struct fasm_file *fasm_file_merge_and_sort_ex(const struct fasm_file *file,
                                              fasm_zero_fn zero_fn,
                                              fasm_sort_key_fn sort_key_fn,
                                              void *user,
                                              struct fasm_error **err);

/**
 * Returns `true` if `line` has a `SetFasmFeature` (`false` for `NULL`).
 *
 * # Safety
 *
 * `line` must be `NULL` or a valid `fasm_line` (see `fasm_line`).
 */
FASM_API bool fasm_line_has_set_feature(const struct fasm_line *line);

/**
 * Returns the `SetFasmFeature` of `line`, borrowed from `line`, or `NULL`
 * if it has none (or `line` is `NULL`).
 *
 * # Safety
 *
 * `line` must be `NULL` or a valid `fasm_line` (see `fasm_line`).
 */
FASM_API const struct fasm_set_feature *fasm_line_set_feature(const struct fasm_line *line);

/**
 * Returns the number of annotations of `line` (0 when it has no
 * `{ ... }` block, or `line` is `NULL`).
 *
 * # Safety
 *
 * `line` must be `NULL` or a valid `fasm_line` (see `fasm_line`).
 */
FASM_API size_t fasm_line_annotation_count(const struct fasm_line *line);

/**
 * Stores annotation `index` (0 based, in file order) of `line` in `*out`
 * and returns `true`; the strings are borrowed from `line`.
 *
 * Returns `false` (leaving `*out` unchanged) if `line` or `out` is `NULL`
 * or `index >= fasm_line_annotation_count(line)`.
 *
 * # Safety
 *
 * `line` must be `NULL` or a valid `fasm_line`; `out` must be `NULL` or
 * writable.
 */
FASM_API
bool fasm_line_annotation(const struct fasm_line *line,
                          size_t index,
                          struct fasm_annotation *out);

/**
 * Returns `true` if `line` has a comment (`#`, possibly with empty text).
 * `false` for `NULL`.
 *
 * # Safety
 *
 * `line` must be `NULL` or a valid `fasm_line` (see `fasm_line`).
 */
FASM_API bool fasm_line_has_comment(const struct fasm_line *line);

/**
 * Stores the comment text of `line` (everything after `#`, verbatim,
 * borrowed from `line`, not NUL terminated) in `*out` and returns
 * `true`.
 *
 * Returns `false` and stores an empty view (`NULL`, 0) if `line` has no
 * comment or is `NULL`; `out` may be `NULL` to only test for a comment.
 *
 * # Safety
 *
 * `line` must be `NULL` or a valid `fasm_line`; `out` must be `NULL` or
 * writable.
 */
FASM_API bool fasm_line_comment(const struct fasm_line *line, struct fasm_str *out);

/**
 * Returns the length in bytes of the feature name of `sf` (0 for
 * `NULL`).
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`.
 */
FASM_API size_t fasm_set_feature_name_len(const struct fasm_set_feature *sf);

/**
 * Copies the feature name of `sf` into `buf` with `snprintf` semantics
 * and returns its full length in bytes (not counting the NUL).
 *
 * Feature names are stored interned and split at `.`, so there is no
 * contiguous string to borrow; this copies without allocating. If
 * `buf_len > 0`, at most `buf_len - 1` bytes are copied and a NUL is
 * appended; the name was truncated if the return value is `>= buf_len`.
 * `buf` may be `NULL` when `buf_len` is 0 (to query the length). Returns 0
 * for a `NULL` `sf` (and stores an empty string if `buf_len > 0`).
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`; `buf` must be valid
 * for writing `buf_len` bytes (or `NULL` with `buf_len == 0`).
 */
FASM_API size_t fasm_set_feature_name(const struct fasm_set_feature *sf, char *buf, size_t buf_len);

/**
 * Returns the feature name of `sf` as a new `fasm_string` (free with
 * `fasm_string_free`), or `NULL` if `sf` is `NULL`.
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`.
 */
FASM_API struct fasm_string *fasm_set_feature_name_string(const struct fasm_set_feature *sf);

/**
 * Returns `true` if `sf` has a `FeatureAddress` (`FEATURE[start]` or
 * `FEATURE[end:start]`). `false` for `NULL`.
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`.
 */
FASM_API bool fasm_set_feature_has_start(const struct fasm_set_feature *sf);

/**
 * Returns the start (low) bit of the address of `sf`, or 0 if it has no
 * address (check `fasm_set_feature_has_start`) or `sf` is `NULL`.
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`.
 */
FASM_API uint32_t fasm_set_feature_start(const struct fasm_set_feature *sf);

/**
 * Returns `true` if `sf` has an end (high) bit (`FEATURE[end:start]`).
 * `false` for `NULL`.
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`.
 */
FASM_API bool fasm_set_feature_has_end(const struct fasm_set_feature *sf);

/**
 * Returns the end (high) bit of the address of `sf`, or 0 if it has none
 * (check `fasm_set_feature_has_end`) or `sf` is `NULL`.
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`.
 */
FASM_API uint32_t fasm_set_feature_end(const struct fasm_set_feature *sf);

/**
 * Returns the format the value of `sf` was written in, or
 * `FASM_VALUE_FORMAT_NONE` if no value was written (or `sf` is `NULL`).
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`.
 */
FASM_API enum fasm_value_format fasm_set_feature_value_format(const struct fasm_set_feature *sf);

/**
 * Returns the width in bits of the address of `sf`: 1 without an address
 * or with a single bit address, `end - start + 1` for a range (Python:
 * `fasm.set_feature_width`). 0 for `NULL`.
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`.
 */
FASM_API uint32_t fasm_set_feature_width(const struct fasm_set_feature *sf);

/**
 * Returns the number of bits needed to hold the value of `sf`: 0 for the
 * value 0, otherwise one more than the index of its highest set bit. 0
 * for `NULL`.
 *
 * Values have no size limit (a 256 bit BRAM `INIT` value is common); use
 * `fasm_set_feature_value_bytes_le` or `fasm_set_feature_value_bit` for
 * values wider than 64 bits.
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`.
 */
FASM_API uint32_t fasm_set_feature_value_bits(const struct fasm_set_feature *sf);

/**
 * Stores the value of `sf` in `*out` and returns `true` if it fits in 64
 * bits; returns `false` (leaving `*out` unchanged) if it does not, or
 * `sf` or `out` is `NULL`.
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`; `out` must be `NULL`
 * or writable.
 */
FASM_API bool fasm_set_feature_value_u64(const struct fasm_set_feature *sf, uint64_t *out);

/**
 * Returns bit `index` of the value of `sf` (bit 0 is the least
 * significant); `false` beyond `fasm_set_feature_value_bits` and for
 * `NULL`.
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`.
 */
FASM_API bool fasm_set_feature_value_bit(const struct fasm_set_feature *sf, uint32_t index);

/**
 * Copies the value of `sf` into `buf` as a little endian byte string and
 * returns the number of bytes the value needs: `(value_bits + 7) / 8`, so
 * 0 for the value 0 (and for `NULL`).
 *
 * If `buf_len` is at least the returned size, the value is written to
 * `buf[0..size]` and the rest of `buf[0..buf_len]` is zero filled (so a
 * 32 byte buffer receives any value of up to 256 bits, zero extended).
 * Otherwise `buf` is not touched: call again with a large enough buffer.
 * `buf` may be `NULL` when `buf_len` is 0 (to query the size).
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`; `buf` must be valid
 * for writing `buf_len` bytes (or `NULL` with `buf_len == 0`).
 */
FASM_API
size_t fasm_set_feature_value_bytes_le(const struct fasm_set_feature *sf,
                                       uint8_t *buf,
                                       size_t buf_len);

/**
 * Returns the value of `sf` as digits in `radix` (2, 8, 10 or 16), with no
 * prefix or width and without leading zeros (`"0"` for 0), hex digits in
 * upper case if `uppercase`. Free with `fasm_string_free`.
 *
 * Returns `NULL` (and sets `*err` to a `FASM_ERR_INVALID_ARG` error) if
 * `sf` is `NULL` or `radix` is not supported.
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`; `err` must be `NULL`
 * or writable.
 */
FASM_API
struct fasm_string *fasm_set_feature_value_to_string(const struct fasm_set_feature *sf,
                                                     uint32_t radix,
                                                     bool uppercase,
                                                     struct fasm_error **err);

/**
 * Renders all lines of `file` as FASM text (Python:
 * `fasm.fasm_tuple_to_string(model, canonical)`): one line per
 * `fasm_line`, each ending in `\n` (an empty file gives `"\n"`), with
 * optional whitespace normalised to single spaces.
 *
 * With `canonical`, every set feature is expanded to one line per set
 * bit (`FEATURE[bit]`, or `FEATURE` for bit 0 of a feature without
 * address), cleared bits, annotations and comments are dropped, and the
 * lines are sorted and deduplicated.
 *
 * Returns a new `fasm_string` (free with `fasm_string_free`), or `NULL`
 * on error (`FASM_ERR_INVALID_ARG` for a `NULL` `file`, `FASM_ERR_OUTPUT`
 * if a feature cannot be formatted).
 *
 * # Safety
 *
 * `file` must be `NULL` or a live `fasm_file`; `err` must be `NULL` or
 * writable.
 */
FASM_API
struct fasm_string *fasm_file_to_string(const struct fasm_file *file,
                                        bool canonical,
                                        struct fasm_error **err);

/**
 * Renders one line (Python: `fasm.fasm_line_to_string`, whose list of
 * strings is joined with `\n` here, without a trailing `\n`).
 *
 * Without `canonical` this is exactly one line of text (possibly empty,
 * for a blank line). With `canonical` it is the canonical lines of the
 * line's set feature (none, i.e. an empty string, for a line without one
 * or with the value 0), in bit order and not deduplicated.
 *
 * Returns a new `fasm_string`, or `NULL` on error (as
 * `fasm_file_to_string`).
 *
 * # Safety
 *
 * `line` must be `NULL` or a valid `fasm_line`; `err` must be `NULL` or
 * writable.
 */
FASM_API
struct fasm_string *fasm_line_to_string(const struct fasm_line *line,
                                        bool canonical,
                                        struct fasm_error **err);

/**
 * Renders a set feature (Python: `fasm.set_feature_to_str(set_feature,
 * check_if_canonical)`), e.g. `A.B[7:0] = 8'hFF`.
 *
 * With `check_if_canonical`, a feature that is not in canonical form
 * (wider than one bit, with an end address, a start address of 0 or a
 * written value) is `FASM_ERR_OUTPUT`.
 *
 * Returns a new `fasm_string`, or `NULL` on error.
 *
 * # Safety
 *
 * `sf` must be `NULL` or a valid `fasm_set_feature`; `err` must be `NULL`
 * or writable.
 */
FASM_API
struct fasm_string *fasm_set_feature_to_string(const struct fasm_set_feature *sf,
                                               bool check_if_canonical,
                                               struct fasm_error **err);

/**
 * Parses the FASM text `text[0..len]` (UTF-8, need not be NUL terminated)
 * into a new `fasm_file`, stored in `*out` (Python:
 * `fasm.parse_fasm_string`).
 *
 * A UTF-8 byte order mark at the start is skipped. Invalid UTF-8 in a
 * comment or annotation value is `FASM_ERR_UTF8`; any other invalid input
 * is `FASM_ERR_PARSE`. On failure `*out` is set to `NULL` and, if `err` is
 * not `NULL`, `*err` receives the error (with `fasm_error_line` /
 * `fasm_error_column`); on success `*out` owns the new file (free with
 * `fasm_file_free`) and `*err` is set to `NULL`.
 *
 * Returns `FASM_ERR_INVALID_ARG` if `out` is `NULL`, or `text` is `NULL`
 * with a non-zero `len`.
 *
 * # Safety
 *
 * `text` must be `NULL` (with `len == 0`) or valid for reading `len`
 * bytes; `out` must be `NULL` or writable; `err` must be `NULL` or
 * writable.
 */
FASM_API
enum fasm_status fasm_parse_string(const char *text,
                                   size_t len,
                                   struct fasm_file **out,
                                   struct fasm_error **err);

/**
 * Reads and parses the FASM file `path` (NUL terminated; any bytes on
 * Unix, UTF-8 on other systems) into a new `fasm_file`, stored in `*out`
 * (Python: `fasm.parse_fasm_filename`).
 *
 * A file that cannot be read is `FASM_ERR_IO` (line and column 0);
 * otherwise as `fasm_parse_string`.
 *
 * # Safety
 *
 * `path` must be `NULL` or a NUL terminated string; `out` and `err` must
 * be `NULL` or writable.
 */
FASM_API
enum fasm_status fasm_parse_file(const char *path,
                                 struct fasm_file **out,
                                 struct fasm_error **err);

/**
 * Parses the FASM text `text[0..len]` like `fasm_parse_string`, but
 * instead of building a `fasm_file` calls `callback` for each line (see
 * `fasm_line_callback`), which avoids holding the whole model in memory.
 *
 * Lines before a parse error are passed to `callback`; the error is then
 * returned (`FASM_ERR_PARSE` / `FASM_ERR_UTF8`, with `*err` set). Returns
 * `FASM_OK` when the whole input was parsed or `callback` returned
 * `false`, and `FASM_ERR_INVALID_ARG` for a `NULL` `callback`, or a
 * `NULL` `text` with a non-zero `len`.
 *
 * # Safety
 *
 * `text` must be `NULL` (with `len == 0`) or valid for reading `len`
 * bytes; `callback` must be `NULL` or a function that can be called with
 * `user`; `err` must be `NULL` or writable.
 */
FASM_API
enum fasm_status fasm_parse_string_cb(const char *text,
                                      size_t len,
                                      fasm_line_callback callback,
                                      void *user,
                                      struct fasm_error **err);

/**
 * Reads the FASM file `path` (see `fasm_parse_file`) and streams its
 * lines to `callback` (see `fasm_parse_string_cb`).
 *
 * # Safety
 *
 * `path` must be `NULL` or a NUL terminated string; `callback` must be
 * `NULL` or a function that can be called with `user`; `err` must be
 * `NULL` or writable.
 */
FASM_API
enum fasm_status fasm_parse_file_cb(const char *path,
                                    fasm_line_callback callback,
                                    void *user,
                                    struct fasm_error **err);

/**
 * Returns the NUL terminated text of `s`, owned by `s` (valid until
 * `fasm_string_free`). Returns an empty string for a `NULL` `s`.
 *
 * # Safety
 *
 * `s` must be `NULL` or a live `fasm_string` from this library.
 */
FASM_API const char *fasm_string_data(const struct fasm_string *s);

/**
 * Returns the length of `s` in bytes, not counting the NUL terminator (0
 * for a `NULL` `s`).
 *
 * # Safety
 *
 * `s` must be `NULL` or a live `fasm_string` from this library.
 */
FASM_API size_t fasm_string_len(const struct fasm_string *s);

/**
 * Frees `s`. `NULL` is accepted (no-op).
 *
 * # Safety
 *
 * `s` must be `NULL` or a live `fasm_string` from this library that is not
 * used afterwards (in particular not freed twice).
 */
FASM_API void fasm_string_free(struct fasm_string *s);

/**
 * Returns the data of `b` (owned by `b`, valid until `fasm_bytes_free`;
 * `NULL` for a `NULL` or empty `b`).
 *
 * # Safety
 *
 * `b` must be `NULL` or a live `fasm_bytes` from this library.
 */
FASM_API const uint8_t *fasm_bytes_data(const struct fasm_bytes *b);

/**
 * Returns the length of `b` in bytes (0 for a `NULL` `b`).
 *
 * # Safety
 *
 * `b` must be `NULL` or a live `fasm_bytes` from this library.
 */
FASM_API size_t fasm_bytes_len(const struct fasm_bytes *b);

/**
 * Frees `b`. `NULL` is accepted (no-op).
 *
 * # Safety
 *
 * `b` must be `NULL` or a live `fasm_bytes` from this library that is not
 * used afterwards.
 */
FASM_API void fasm_bytes_free(struct fasm_bytes *b);

/**
 * Creates an assembler for the part `db` was opened for, stored in
 * `*out` (free with `fasm_xilinx_assembler_free`). For an UltraScale or
 * UltraScale+ database it uses prjuray's semantics (see
 * `fasm_xilinx_assembler_set_prjuray`), like the `fasm2frames` tool.
 *
 * Errors: `FASM_ERR_DB` if `db` was opened without a part.
 *
 * # Safety
 *
 * `db` must be `NULL` or a live database; `out` and `err` `NULL` or
 * writable.
 */
FASM_API
enum fasm_status fasm_xilinx_assembler_new(const struct fasm_xilinx_database *db,
                                           struct fasm_xilinx_assembler **out,
                                           struct fasm_error **err);

/**
 * Frees `assembler`. `NULL` is accepted (no-op).
 *
 * # Safety
 *
 * `assembler` must be `NULL` or live, and not used afterwards.
 */
FASM_API void fasm_xilinx_assembler_free(struct fasm_xilinx_assembler *assembler);

/**
 * Selects prjuray's assembler semantics (`true`: bits beyond the end of a
 * frame are kept, conflicts are reported in 16-bit words) or prjxray's
 * (`false`: such bits are dropped with a warning).
 *
 * # Safety
 *
 * `assembler` must be `NULL` or live and not used by anything else
 * during the call.
 */
FASM_API
void fasm_xilinx_assembler_set_prjuray(struct fasm_xilinx_assembler *assembler,
                                       bool prjuray);

/**
 * `FasmAssembler.parse_fasm_filename`: parses the whole FASM file `path`
 * (NUL terminated; a syntax error is reported before anything is
 * assembled) and adds its lines.
 *
 * Errors: `FASM_ERR_IO`, `FASM_ERR_PARSE` (with a position),
 * `FASM_ERR_LOOKUP` (every feature missing from the database, one per
 * line of the message), `FASM_ERR_INCONSISTENT_BITS`,
 * `FASM_ERR_ASSEMBLER` (kind `KeyError`: an unknown tile or tile type).
 *
 * # Safety
 *
 * `assembler` must be `NULL` or live and exclusive; `path` `NULL` or NUL
 * terminated; `err` `NULL` or writable.
 */
FASM_API
enum fasm_status fasm_xilinx_assembler_parse_file(struct fasm_xilinx_assembler *assembler,
                                                  const char *path,
                                                  struct fasm_error **err);

/**
 * `fasm_xilinx_assembler_parse_file` for the FASM text `text[0..len]`.
 *
 * # Safety
 *
 * `assembler` must be `NULL` or live and exclusive; `text` valid for
 * `len` bytes; `err` `NULL` or writable.
 */
FASM_API
enum fasm_status fasm_xilinx_assembler_parse_string(struct fasm_xilinx_assembler *assembler,
                                                    const char *text,
                                                    size_t len,
                                                    struct fasm_error **err);

/**
 * Adds the lines of the parsed model `file` (`fasm_parse_*`,
 * `fasm_file_push_line`, ...) like `FasmAssembler.add_fasm_line`; the
 * features missing from the database are reported together at the end
 * (`FASM_ERR_LOOKUP`).
 *
 * # Safety
 *
 * `assembler` must be `NULL` or live and exclusive; `file` `NULL` or a
 * live `fasm_file`; `err` `NULL` or writable.
 */
FASM_API
enum fasm_status fasm_xilinx_assembler_add_file(struct fasm_xilinx_assembler *assembler,
                                                const struct fasm_file *file,
                                                struct fasm_error **err);

/**
 * Adds the lines of the part's `required_features.fasm`, like
 * `fasm2frames` does after the FASM file.
 *
 * # Safety
 *
 * `assembler` must be `NULL` or live and exclusive; `err` `NULL` or
 * writable.
 */
FASM_API
enum fasm_status fasm_xilinx_assembler_add_required_features(struct fasm_xilinx_assembler *assembler,
                                                             struct fasm_error **err);

/**
 * `FasmAssembler.mark_roi_frames`: marks every frame of every bus of the
 * tiles with `x1 <= grid_x <= x2` and `y1 <= grid_y <= y2` in use, so
 * that sparse frames include them.
 *
 * # Safety
 *
 * `assembler` must be `NULL` or live and exclusive; `err` `NULL` or
 * writable.
 */
FASM_API
enum fasm_status fasm_xilinx_assembler_mark_roi(struct fasm_xilinx_assembler *assembler,
                                                double x1,
                                                double x2,
                                                double y1,
                                                double y2,
                                                struct fasm_error **err);

/**
 * The STEPDOWN propagation of `fasm2frames` (call it after all features
 * have been added): if a used IOB of an IO bank sets a feature whose name
 * contains `STEPDOWN`, every unused IOB site of the bank gets the same
 * feature(s) and the bank's `HCLK_IOI3` tile gets `STEPDOWN`.
 *
 * # Safety
 *
 * `assembler` must be `NULL` or live and exclusive; `err` `NULL` or
 * writable.
 */
FASM_API
enum fasm_status fasm_xilinx_assembler_propagate_stepdown(struct fasm_xilinx_assembler *assembler,
                                                          struct fasm_error **err);

/**
 * Returns the number of warnings so far (bits beyond the end of a frame
 * that prjxray drops with `frame_set: invalid word address ...`; 0 for
 * `NULL`).
 *
 * # Safety
 *
 * `assembler` must be `NULL` or live.
 */
FASM_API size_t fasm_xilinx_assembler_warning_count(const struct fasm_xilinx_assembler *assembler);

/**
 * Returns warning `index` (borrowed, not NUL terminated: valid until the
 * assembler is modified or freed; empty if out of range).
 *
 * # Safety
 *
 * `assembler` must be `NULL` or live.
 */
FASM_API
struct fasm_str fasm_xilinx_assembler_warning(const struct fasm_xilinx_assembler *assembler,
                                              size_t index);

/**
 * `FasmAssembler.get_frames(sparse)`: every frame of the part (`sparse`
 * false, zero filled) or only the frames of the buses that were written
 * or marked, with the set bits applied, as new frames stored in `*out`.
 *
 * # Safety
 *
 * `assembler` must be `NULL` or live; `out` and `err` `NULL` or writable.
 */
FASM_API
enum fasm_status fasm_xilinx_assembler_get_frames(const struct fasm_xilinx_assembler *assembler,
                                                  bool sparse,
                                                  struct fasm_xilinx_frames **out,
                                                  struct fasm_error **err);

/**
 * The whole FASM -> frames flow of the `fasm2frames` tool
 * (`xc_fasm.fasm2frames.fasm2frames`) for the part `db` was opened for,
 * on the FASM file `path` (NUL terminated): the ROI, the part's required
 * features, the PUDC_B pullup and the STEPDOWN propagation; on an
 * UltraScale(+) database, prjuray's flow (like the tool). The frames are
 * stored in `*out`; byte for byte the tool's `.frm` output through
 * `fasm_xilinx_frames_to_frm`.
 *
 * Errors: as `fasm_xilinx_assembler_parse_file`, plus `FASM_ERR_IO` /
 * `FASM_ERR_ASSEMBLER` for the ROI file and `FASM_ERR_DB`.
 *
 * # Safety
 *
 * `db` must be `NULL` or a live database; `path` `NULL` or NUL
 * terminated; `options` `NULL` or valid (its `roi` `NULL` or NUL
 * terminated, `warning` `NULL` or callable with `user`); `out` and `err`
 * `NULL` or writable.
 */
FASM_API
enum fasm_status fasm_xilinx_fasm2frames_file(const struct fasm_xilinx_database *db,
                                              const char *path,
                                              const struct fasm_xilinx_fasm2frames_options *options,
                                              struct fasm_xilinx_frames **out,
                                              struct fasm_error **err);

/**
 * `fasm_xilinx_fasm2frames_file` for the FASM text `text[0..len]`.
 *
 * # Safety
 *
 * As for `fasm_xilinx_fasm2frames_file`, with `text` valid for `len`
 * bytes.
 */
FASM_API
enum fasm_status fasm_xilinx_fasm2frames_string(const struct fasm_xilinx_database *db,
                                                const char *text,
                                                size_t len,
                                                const struct fasm_xilinx_fasm2frames_options *options,
                                                struct fasm_xilinx_frames **out,
                                                struct fasm_error **err);

/**
 * Stores the part of `db` (its `part.yaml`, else `part.json` frame tree)
 * in `*out` (free with `fasm_xilinx_part_free`; it shares the ownership
 * of `db`). `FASM_ERR_DB` if the part has no frame tree.
 *
 * # Safety
 *
 * `db` must be `NULL` or live; `out` and `err` `NULL` or writable.
 */
FASM_API
enum fasm_status fasm_xilinx_part_from_database(const struct fasm_xilinx_database *db,
                                                struct fasm_xilinx_part **out,
                                                struct fasm_error **err);

/**
 * Reads the part file `path` (a `part.yaml`, NUL terminated) like the
 * `--part_file` of `xc7frames2bit` / `xcframes2bit`: a file tagged with
 * an architecture (`!<xilinx/xc7series/part>`, `xcuseries`,
 * `xcupseries`) is of that architecture, an untagged one is read as
 * `architecture` (a `fasm_xilinx_architecture` value). The part is
 * stored in `*out`. `FASM_ERR_DB` if it cannot be read.
 *
 * # Safety
 *
 * `path` must be `NULL` or NUL terminated; `out` and `err` `NULL` or
 * writable.
 */
FASM_API
enum fasm_status fasm_xilinx_part_read_yaml(const char *path,
                                            int32_t architecture,
                                            struct fasm_xilinx_part **out,
                                            struct fasm_error **err);

/**
 * Frees `part`. `NULL` is accepted (no-op).
 *
 * # Safety
 *
 * `part` must be `NULL` or live, and not used afterwards.
 */
FASM_API void fasm_xilinx_part_free(struct fasm_xilinx_part *part);

/**
 * Returns the architecture of `part` (`FASM_XILINX_SERIES7` for `NULL`).
 *
 * # Safety
 *
 * `part` must be `NULL` or live.
 */
FASM_API
enum fasm_xilinx_architecture fasm_xilinx_part_architecture(const struct fasm_xilinx_part *part);

/**
 * Writes `frames` as a `.bit` bitstream for `part` into a new
 * `fasm_bytes` stored in `*out`, byte for byte like `xc7frames2bit`
 * (Series7) and prjuray-tools' `xcframes2bit` (UltraScale, UltraScale+):
 * the `.bit` header, the configuration packets with the part's IDCODE and
 * every frame of the part (missing frames zero filled) with its ECC.
 *
 * Errors: `FASM_ERR_BITSTREAM` (a part of another architecture than the
 * format's, frames of another size), `FASM_ERR_INVALID_ARG`.
 *
 * # Safety
 *
 * `part` and `frames` must be `NULL` or live; `options` `NULL` or valid
 * (its strings `NULL` or NUL terminated); `out` and `err` `NULL` or
 * writable.
 */
FASM_API
enum fasm_status fasm_xilinx_bitstream_write(const struct fasm_xilinx_part *part,
                                             const struct fasm_xilinx_frames *frames,
                                             const struct fasm_xilinx_bitstream_options *options,
                                             struct fasm_bytes **out,
                                             struct fasm_error **err);

/**
 * `fasm_xilinx_bitstream_write` to the file `path` (NUL terminated;
 * `FASM_ERR_IO` if it cannot be written).
 *
 * # Safety
 *
 * As for `fasm_xilinx_bitstream_write`; `path` `NULL` or NUL terminated.
 */
FASM_API
enum fasm_status fasm_xilinx_bitstream_write_file(const struct fasm_xilinx_part *part,
                                                  const struct fasm_xilinx_frames *frames,
                                                  const struct fasm_xilinx_bitstream_options *options,
                                                  const char *path,
                                                  struct fasm_error **err);

/**
 * Reads the frames of the bitstream `data[0..len]` (a `.bit` file, or
 * raw configuration data: everything after the first sync word) for
 * `part` in `format` (a `fasm_xilinx_bitstream_format` value), like
 * `bitread`, into new frames stored in `*out`: every frame the bitstream
 * writes, with the ECC bits cleared when `clear_ecc` (which gives back
 * the frames `fasm2frames` wrote, `bitread --frm_out`) and without the
 * all zero frames when `skip_zero`.
 *
 * Errors: `FASM_ERR_BITSTREAM` (no sync word, an IDCODE that is not the
 * part's, a part of another architecture than the format's).
 *
 * # Safety
 *
 * `part` must be `NULL` or live; `data` valid for `len` bytes; `out` and
 * `err` `NULL` or writable.
 */
FASM_API
enum fasm_status fasm_xilinx_bitstream_read(const struct fasm_xilinx_part *part,
                                            const uint8_t *data,
                                            size_t len,
                                            int32_t format,
                                            bool clear_ecc,
                                            bool skip_zero,
                                            struct fasm_xilinx_frames **out,
                                            struct fasm_error **err);

/**
 * `fasm_xilinx_bitstream_read` for the file `path` (NUL terminated;
 * `FASM_ERR_IO` if it cannot be read).
 *
 * # Safety
 *
 * As for `fasm_xilinx_bitstream_read`; `path` `NULL` or NUL terminated.
 */
FASM_API
enum fasm_status fasm_xilinx_bitstream_read_file(const struct fasm_xilinx_part *part,
                                                 const char *path,
                                                 int32_t format,
                                                 bool clear_ecc,
                                                 bool skip_zero,
                                                 struct fasm_xilinx_frames **out,
                                                 struct fasm_error **err);

/**
 * Opens the database family directory `db_root` (e.g.
 * `prjxray-db/artix7`, `prjuray-db/zynqusp`; NUL terminated) for `part`
 * (e.g. `xc7a35tcsg324-1`, NUL terminated UTF-8; `NULL` loads only the
 * tile types, which cannot assemble) from its text files, and stores the
 * new database in `*out` (free with `fasm_xilinx_database_free`).
 *
 * Errors: `FASM_ERR_DB` (a missing or malformed file, an unknown part,
 * not a database directory), `FASM_ERR_INVALID_ARG`, `FASM_ERR_UTF8`.
 *
 * # Safety
 *
 * `db_root` and `part` must be `NULL` or NUL terminated; `out` and `err`
 * must be `NULL` or writable.
 */
FASM_API
enum fasm_status fasm_xilinx_database_open(const char *db_root,
                                           const char *part,
                                           struct fasm_xilinx_database **out,
                                           struct fasm_error **err);

/**
 * `fasm_xilinx_database_open` through the binary database cache: the
 * part is loaded from its cache file when none of its source files
 * changed, else from the text files (and the cache file is rewritten);
 * the result is the same. `cache_dir` (NUL terminated) is the cache
 * directory; `NULL` uses the settings of the command line tools
 * (`$FASM_XDB_CACHE`, else `$XDG_CACHE_HOME/fasm/db`, else
 * `~/.cache/fasm/db`; `FASM_XDB_CACHE=0` disables the cache). Problems
 * with the cache itself are never errors.
 *
 * # Safety
 *
 * As for `fasm_xilinx_database_open`; `cache_dir` must be `NULL` or NUL
 * terminated.
 */
FASM_API
enum fasm_status fasm_xilinx_database_open_cached(const char *db_root,
                                                  const char *part,
                                                  const char *cache_dir,
                                                  struct fasm_xilinx_database **out,
                                                  struct fasm_error **err);

/**
 * Frees `db`. `NULL` is accepted (no-op). Assemblers and parts made from
 * it stay valid.
 *
 * # Safety
 *
 * `db` must be `NULL` or a live `fasm_xilinx_database` that is not used
 * afterwards.
 */
FASM_API void fasm_xilinx_database_free(struct fasm_xilinx_database *db);

/**
 * Returns the architecture of `db` (`FASM_XILINX_SERIES7` for `NULL`).
 *
 * # Safety
 *
 * `db` must be `NULL` or a live `fasm_xilinx_database`.
 */
FASM_API
enum fasm_xilinx_architecture fasm_xilinx_database_architecture(const struct fasm_xilinx_database *db);

/**
 * Returns the number of 32-bit words per frame of the architecture of
 * `db` (101, 123 or 93; 0 for `NULL`).
 *
 * # Safety
 *
 * `db` must be `NULL` or a live `fasm_xilinx_database`.
 */
FASM_API size_t fasm_xilinx_database_words_per_frame(const struct fasm_xilinx_database *db);

/**
 * Returns the part name of `db` (NUL terminated, owned by `db`), or
 * `NULL` if it was opened without a part (or for a `NULL` `db`).
 *
 * # Safety
 *
 * `db` must be `NULL` or a live `fasm_xilinx_database`.
 */
FASM_API const char *fasm_xilinx_database_part(const struct fasm_xilinx_database *db);

/**
 * Looks up bit `address` of the FASM feature `feature[0..len]`
 * (`TILE.SITE.FEATURE`, UTF-8; `address` is the `N` of `FEATURE[N]`, 0
 * for a feature without one), like the assembler does. Fills `*info`
 * and the first `bits_capacity` bits into `bits` (`info->bit_count` is
 * the total, so a caller can size `bits` with a first call with
 * `bits_capacity` 0; `bits` may be `NULL` then).
 *
 * Errors: `FASM_ERR_ASSEMBLER` (kind `KeyError`) for an unknown tile or
 * tile type, `FASM_ERR_LOOKUP` for a feature that is not in the tile's
 * segbits (`Segment DB <type>, key <type>.<feature> not found`),
 * `FASM_ERR_DB` for a database opened without a part.
 *
 * # Safety
 *
 * `db` must be `NULL` or a live database; `feature` valid for `len`
 * bytes; `info` `NULL` or writable; `bits` `NULL` or writable for
 * `bits_capacity` elements; `err` `NULL` or writable.
 */
FASM_API
enum fasm_status fasm_xilinx_database_lookup(const struct fasm_xilinx_database *db,
                                             const char *feature,
                                             size_t len,
                                             uint32_t address,
                                             struct fasm_xilinx_feature_info *info,
                                             struct fasm_xilinx_bit *bits,
                                             size_t bits_capacity,
                                             struct fasm_error **err);

/**
 * Returns a new, empty set of frames of `words_per_frame` words (101 for
 * Series7, 123 for UltraScale, 93 for UltraScale+), or `NULL` if
 * `words_per_frame` is 0. Free with `fasm_xilinx_frames_free`.
 */
FASM_API struct fasm_xilinx_frames *fasm_xilinx_frames_new(size_t words_per_frame);

/**
 * Frees `frames`. `NULL` is accepted (no-op).
 *
 * # Safety
 *
 * `frames` must be `NULL` or live, and not used afterwards.
 */
FASM_API void fasm_xilinx_frames_free(struct fasm_xilinx_frames *frames);

/**
 * Returns the number of frames (0 for `NULL`).
 *
 * # Safety
 *
 * `frames` must be `NULL` or live.
 */
FASM_API size_t fasm_xilinx_frames_count(const struct fasm_xilinx_frames *frames);

/**
 * Returns the number of 32-bit words per frame (0 for `NULL`).
 *
 * # Safety
 *
 * `frames` must be `NULL` or live.
 */
FASM_API size_t fasm_xilinx_frames_words_per_frame(const struct fasm_xilinx_frames *frames);

/**
 * Returns the address of frame `index` (frames are in ascending address
 * order; 0 if `index` is out of range or `frames` is `NULL`).
 *
 * # Safety
 *
 * `frames` must be `NULL` or live.
 */
FASM_API uint32_t fasm_xilinx_frames_address(const struct fasm_xilinx_frames *frames, size_t index);

/**
 * Returns the `words_per_frame` words of frame `index` (borrowed from
 * `frames`: valid until it is freed or modified), or `NULL` if `index` is
 * out of range or `frames` is `NULL`.
 *
 * # Safety
 *
 * `frames` must be `NULL` or live.
 */
FASM_API
const uint32_t *fasm_xilinx_frames_words(const struct fasm_xilinx_frames *frames,
                                         size_t index);

/**
 * Returns the words of the frame at `address` (borrowed, as
 * `fasm_xilinx_frames_words`), or `NULL` if there is none.
 *
 * # Safety
 *
 * `frames` must be `NULL` or live.
 */
FASM_API
const uint32_t *fasm_xilinx_frames_find(const struct fasm_xilinx_frames *frames,
                                        uint32_t address);

/**
 * Sets the frame at `address` to `words[0..count]` (inserting it if it
 * does not exist). `count` must be the number of words per frame
 * (`FASM_ERR_INVALID_ARG` otherwise).
 *
 * # Safety
 *
 * `frames` must be `NULL` or live and not accessed by anything else
 * during the call; `words` valid for `count` elements; `err` `NULL` or
 * writable.
 */
FASM_API
enum fasm_status fasm_xilinx_frames_set(struct fasm_xilinx_frames *frames,
                                        uint32_t address,
                                        const uint32_t *words,
                                        size_t count,
                                        struct fasm_error **err);

/**
 * Returns `true` if `a` and `b` hold the same frames with the same words
 * (two `NULL`s are equal).
 *
 * # Safety
 *
 * `a` and `b` must be `NULL` or live.
 */
FASM_API
bool fasm_xilinx_frames_equal(const struct fasm_xilinx_frames *a,
                              const struct fasm_xilinx_frames *b);

/**
 * Formats `frames` as `.frm` text (`0x%08X` address, a space, the words
 * as comma separated `0x%08X`, one frame per line; byte for byte what
 * `fasm2frames` writes) into a new `fasm_string` stored in `*out`.
 *
 * # Safety
 *
 * `frames` must be `NULL` or live; `out` and `err` `NULL` or writable.
 */
FASM_API
enum fasm_status fasm_xilinx_frames_to_frm(const struct fasm_xilinx_frames *frames,
                                           struct fasm_string **out,
                                           struct fasm_error **err);

/**
 * Writes `frames` as a `.frm` file to `path` (NUL terminated).
 * `FASM_ERR_IO` if it cannot be written.
 *
 * # Safety
 *
 * `frames` must be `NULL` or live; `path` `NULL` or NUL terminated; `err`
 * `NULL` or writable.
 */
FASM_API
enum fasm_status fasm_xilinx_frames_write_frm(const struct fasm_xilinx_frames *frames,
                                              const char *path,
                                              struct fasm_error **err);

/**
 * Parses `.frm` text `text[0..len]` with `words_per_frame` words per
 * frame, like `xc7frames2bit` reads its `--frm_file` (`#` lines are
 * comments; a line with another number of words is skipped with a
 * warning passed to `warning`, which may be `NULL`; the first of two
 * frames with the same address wins), into new frames stored in `*out`.
 * `FASM_ERR_FRM` (with `fasm_error_line`) for a number that does not
 * parse.
 *
 * # Safety
 *
 * `text` valid for `len` bytes; `warning` `NULL` or callable with
 * `user`; `out` and `err` `NULL` or writable.
 */
FASM_API
enum fasm_status fasm_xilinx_frames_parse_frm(const char *text,
                                              size_t len,
                                              size_t words_per_frame,
                                              fasm_xilinx_warning_fn warning,
                                              void *user,
                                              struct fasm_xilinx_frames **out,
                                              struct fasm_error **err);

/**
 * `fasm_xilinx_frames_parse_frm` for the file `path` (NUL terminated;
 * `FASM_ERR_IO` if it cannot be read).
 *
 * # Safety
 *
 * `path` `NULL` or NUL terminated; otherwise as
 * `fasm_xilinx_frames_parse_frm`.
 */
FASM_API
enum fasm_status fasm_xilinx_frames_read_frm(const char *path,
                                             size_t words_per_frame,
                                             fasm_xilinx_warning_fn warning,
                                             void *user,
                                             struct fasm_xilinx_frames **out,
                                             struct fasm_error **err);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* FASM_FASM_H */
