#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright 2017-2022 F4PGA Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
"""Generates rust/fasm-cli/src/unicode_tables.rs.

The `fasm` command line tool emulates Python's argparse, which depends on
three Unicode properties of the Python interpreter running the original
tool:

* `str.isprintable()` (used by `repr()` in "ignored explicit argument %r"),
* the `Nd` (decimal digit) category (regex `\\d` in argparse's negative
  number matcher, and `int()` when parsing the `COLUMNS` variable),
* `str.isspace()` (`int()` strips it).

Run it with the Python the original tool runs with (the oracle, Python 3.11,
Unicode 14.0.0) so the tables match it exactly:

    tests/oracle/venv/bin/python rust/fasm-cli/tools/gen_unicode_tables.py \\
        > rust/fasm-cli/src/unicode_tables.rs
    cargo fmt --all

The committed file is the rustfmt formatted output (`cargo fmt --all
--check` must pass), so always run `cargo fmt` after generating it.
"""
import sys
import unicodedata

HEADER = """\
// Copyright 2017-2022 F4PGA Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

//! Unicode property tables of the Python interpreter the original `fasm`
//! tool runs with (Python {pyver}, Unicode {univer}).
//!
//! GENERATED by `rust/fasm-cli/tools/gen_unicode_tables.py`; do not edit.
"""


def ranges(codepoints):
    out = []
    start = prev = None
    for c in codepoints:
        if start is None:
            start = prev = c
        elif c == prev + 1:
            prev = c
        else:
            out.append((start, prev))
            start = prev = c
    if start is not None:
        out.append((start, prev))
    return out


def main():
    w = sys.stdout.write
    w(
        HEADER.format(
            pyver=sys.version.split()[0],
            univer=unicodedata.unidata_version))

    nonprintable = ranges(
        c for c in range(0x80, 0x110000) if not chr(c).isprintable())
    w('\n/// Inclusive ranges of the non-ASCII code points for which\n')
    w('/// `str.isprintable()` is false (sorted, disjoint).\n')
    w('pub const NON_PRINTABLE: &[(u32, u32)] = &[\n')
    for a, b in nonprintable:
        w('    (0x{:04X}, 0x{:04X}),\n'.format(a, b))
    w('];\n')

    nd = [
        c for c in range(0x110000) if unicodedata.category(chr(c)) == 'Nd'
    ]
    assert len(nd) % 10 == 0
    zeros = nd[::10]
    for z in zeros:
        for i in range(10):
            assert unicodedata.decimal(chr(z + i)) == i, hex(z + i)
    decimal = {
        c
        for c in range(0x110000) if unicodedata.decimal(chr(c), -1) >= 0
    }
    assert decimal == set(nd)
    w('\n/// The code points of the digit zero of every run of ten `Nd`\n')
    w('/// (decimal digit) code points `0`..=`9` (sorted); these are also\n')
    w('/// exactly the characters with a decimal value.\n')
    w('pub const DECIMAL_ZEROS: &[u32] = &[\n')
    for z in zeros:
        w('    0x{:04X},\n'.format(z))
    w('];\n')

    space = [c for c in range(0x110000) if chr(c).isspace()]
    w('\n/// The code points for which `str.isspace()` is true (sorted).\n')
    w('pub const WHITESPACE: &[u32] = &[\n')
    for c in space:
        w('    0x{:04X},\n'.format(c))
    w('];\n')


if __name__ == '__main__':
    main()
