#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright 2017-2022 F4PGA Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
"""Differential test of the Rust `fasm2frames` against the reference
(f4pga-xc-fasm's `xc_fasm.fasm2frames` on prjxray, the oracle
`tests/oracle/fasm2frames-oracle`), v1 (T5.4/T5.5).

For every FASM file of the Xilinx corpus

* `tests/corpus/xilinx/<family>/**/*.fasm` with the prjxray-db family
  `<db cache>/prjxray-db/<family>` and the part of `FAMILY_PARTS`
  (skipped with a note when the database has not been fetched,
  `tools/fetch-db.sh prjxray <family>`);
* `tests/corpus/f4pga-xc-fasm/**/*.fasm` with the miniature database
  `rust/fasm-xilinx/testdata/mini-db` (part `xc7`);

both tools are run with each flag set of `VARIANTS` (dense, `--sparse`,
`--emit_pudc_b_pullup`, `--sparse --debug`, and `--sparse --roi
<stem>.roi.json` when that file exists next to the FASM file), writing
the `.frm` to a file, and the results are compared:

* the exit codes must be equal;
* the `.frm` files must be identical, byte for byte (also when the tools
  fail: both create the output file first, so it must be empty);
* stdout (the `--debug` dump) must be identical;
* stderr must be identical after this normalisation (documented in the
  `fasm2frames` section of `docs/rewrite/COMPAT.md`):
  1. the oracle's traceback (`Traceback (most recent call last):` and
     the indented frame lines after it) is removed: the Rust tool prints
     only the last line(s), `<exception type>: <message>`;
  2. parse errors (`Exception: Parse error at L:C - <message>`) are
     compared up to the message: the position must be identical, the
     message texts are the Rust parser's own (like the `fasm` CLI);
  3. database errors: when the oracle fails with an exception outside
     `EXACT_EXCEPTIONS` (it reports a database that cannot be opened with
     assorted Python exceptions, the Rust tool with
     `fasm_xilinx.DbError`), and the Rust tool with
     `fasm_xilinx.DbError`, only the exit codes (1 on both sides) are
     compared;
  4. value range errors (`a = 2`, `a[3:0] = 5'h10`, `a[0:1]`) of the
     reference's ANTLR parser: its assertion fails inside a ctypes
     callback (`Exception ignored on calling ctypes callback function`,
     an `AssertionError` traceback) and the tool then dies with
     `TypeError: 'NoneType' object is not iterable`; the Rust tool reports
     `Exception: Parse error at L:C - <message>` at the value. Both become
     `<value range error>` (like rule 2 of the `fasm` CLI difftest).
  Any other difference of stderr is a failure.

Bitstream tools (T5.6/T5.7), for the prjxray-db families (whose parts
have a `part.yaml`):

* for the `BITSTREAM_VARIANTS` runs that succeed, the reference
  `xc7frames2bit` (`tests/oracle/xc7frames2bit-oracle`) and the Rust
  `xc7frames2bit` both turn the oracle's `.frm` into a `.bit`; the Rust
  tool gets the reference header's date and time through
  `SOURCE_DATE_EPOCH`, so the two files must be identical byte for byte
  (as must stdout, stderr and the exit codes); then the reference and
  the Rust `bitread` read the reference `.bit` with each flag set of
  `BITREAD_FLAGS` and must print the same (stdout, stderr, exit code and
  the `-o` / `--aux` files);
* the reference `xcfasm` (`tests/oracle/xcfasm-oracle`, with `--frm2bit`
  pointing at the reference `xc7frames2bit`) and the Rust `xcfasm` run
  on every FASM file with `XCFASM_VARIANTS`, writing the same `--frm_out`
  and `--bit_out` paths: the `.frm` and `.bit` files (again with the
  reference time injected), stdout, exit codes and stderr (normalised
  like for fasm2frames) must be identical;
* `bitread` also runs on the reference bitstreams of
  `reference_bitstreams()` (the golden smoke bitstream and, from the
  oracle's prjxray checkout, `lib/test_data/configuration_test*.bit` and
  the Series7 bitstreams of `ToolsTestData.tar.gz`, Vivado outputs) with
  every flag set.

All parts of a family (T5.9): with `--family artix7` (`--families
artix7,kintex7,spartan7,zynq7`, a family missing from `--db-cache` is
fetched with `tools/fetch-db.sh` after checking the free space) and
`--all-parts` or `--parts GLOB[,GLOB]`, the corpus of each part is
generated by `tools/gen-xilinx-corpus.py` (`--tiles`, `--seed`,
`--density`, `--max-per-tile`) into `--work-dir` (reused while the
generator, its options and the database are the same) and compared: the
first features file with every `VARIANTS` flag set (dense, sparse and
pudc also through xc7frames2bit and every `BITREAD_FLAGS` set), once more
`--sparse` with `FASM_XDB_CACHE=0` for the Rust tool (every other Rust run
uses a per part cache directory, written by the first run), the other
features files `--sparse` (through xc7frames2bit and two bitread flag
sets), the error files `--sparse`, and xcfasm with `XCFASM_VARIANTS`.
Parts run in parallel (`--jobs`), each part's runs in sequence; a table
per part and the totals are printed (`--json-report` writes them). The
reference results are cached in `<work-dir>/results`, keyed by the
command line, the content of its input files, the reference tools
(wrappers, binaries, venv packages) and the database commit, so a rerun
only runs the Rust tools (`--no-result-cache` runs everything); large
cached outputs are kept as a SHA-256 only. Differences where rule 3 or 4
applied are counted as "explained".

The reference gflags tools print their own path (`argv[0]`) in some
messages; it is replaced by `PROG` on both sides.

Exit status: 0 if every run matches, 1 if any differs, 3 if a tool is
missing. `make xilinx-difftest` builds the Rust tools and runs this.
"""
import argparse
import atexit
import base64
import calendar
import concurrent.futures
import fnmatch
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
import threading
import time
import zlib

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_ORACLE = os.path.join(REPO_ROOT, 'tests', 'oracle',
                              'fasm2frames-oracle')
DEFAULT_RUST = os.path.join(REPO_ROOT, 'target', 'release', 'fasm2frames')
DEFAULT_RUST_DIR = os.path.join(REPO_ROOT, 'target', 'release')
DEFAULT_DB_CACHE = os.environ.get(
    'FASM_DB_CACHE', os.path.join(REPO_ROOT, 'tests', 'oracle', 'build',
                                  'db'))
DEFAULT_WORK_DIR = os.path.join(REPO_ROOT, 'tests', 'oracle', 'build',
                                'difftest-xilinx')
MINI_DB = os.path.join(REPO_ROOT, 'rust', 'fasm-xilinx', 'testdata',
                       'mini-db')

# The part used for the FASM files of each prjxray-db family directory.
FAMILY_PARTS = {
    'artix7': 'xc7a35tcsg324-1',
}

VARIANTS = [
    ('dense', []),
    ('sparse', ['--sparse']),
    ('pudc', ['--emit_pudc_b_pullup']),
    ('debug', ['--sparse', '--debug']),
]

# The fasm2frames variants whose .frm also goes through xc7frames2bit and
# bitread, and the xcfasm variants.
BITSTREAM_VARIANTS = ('dense', 'sparse', 'pudc', 'roi')
XCFASM_VARIANTS = [
    ('dense', []),
    ('sparse', ['--sparse']),
    ('debug', ['--sparse', '--debug', '--emit_pudc_b_pullup']),
]

# bitread flag sets (`-o` and `--aux` get a file name appended).
BITREAD_FLAGS = [
    ['-z', '-y', '-o'],
    ['-z', '-x'],
    ['-z', '-C', '-o'],
    ['-y', '-F', '0x00400000:0x004000ff', '--aux'],
    ['-f', '0x00400000', '-C'],
    ['-p', '-F', '0x00000000:0x0000003f', '-o'],
    ['-C', '-x', '-z', '-o'],
    ['-y', '-F', '0:0xffffffff'],
    ['-y', '-F', '010:0x20'],
    ['-y', '-C', '-F', '0x00400100'],
    ['-f', '0x0040010b', '-o'],
]

# Exceptions whose message the Rust tool reproduces exactly.
EXACT_EXCEPTIONS = {
    'prjxray.fasm_assembler.FasmLookupError',
    'prjxray.fasm_assembler.FasmInconsistentBits',
    'KeyError',
    'IndexError',
    'ValueError',
    'Exception',
    'FileNotFoundError',
    'IsADirectoryError',
    'PermissionError',
    'NotADirectoryError',
}

# Version of the oracle result cache entries (Runner).
CACHE_FORMAT = 1
# Larger cached outputs (compressed, base64) are kept as a hash only.
CACHE_KEEP_LIMIT = 32 * 1024

EXIT_OK = 0
EXIT_DIFFERENCES = 1
EXIT_NOT_SET_UP = 3

RULES = ('1-traceback', '2-parse-message', '3-db-error', '4-value-range')
CTYPES_MARKER = 'Exception ignored on calling ctypes callback function'
NONE_TYPE = "TypeError: 'NoneType' object is not iterable"

PARSE_ERROR_RE = re.compile(r'^Exception: Parse error at (\d+):(\d+) - .*$',
                            re.S)


def strip_traceback(stderr):
    """Rule 1: removes the traceback header and frames."""
    lines = stderr.split('\n')
    out = []
    in_traceback = False
    for line in lines:
        if line == 'Traceback (most recent call last):':
            in_traceback = True
            continue
        if in_traceback and line.startswith(' '):
            continue
        in_traceback = False
        out.append(line)
    return '\n'.join(out)


def exception_type(stderr):
    """The exception type of the last line(s) of a traceback, if any."""
    for line in stderr.split('\n'):
        m = re.match(r'^([A-Za-z_][\w.]*): ', line)
        if m and (m.group(1) in EXACT_EXCEPTIONS or '.' in m.group(1)
                  or m.group(1).endswith('Error')):
            return m.group(1), line
    return None, None


def normalise(stderr, rules):
    """Rule 2: parse error messages."""
    head, sep, tail = stderr.partition('Exception: Parse error at ')
    if sep:
        m = PARSE_ERROR_RE.match(sep + tail)
        if m:
            rules['2-parse-message'] += 1
            return head + 'Exception: Parse error at %s:%s - <message>\n' % (
                m.group(1), m.group(2))
    return stderr


class Runner(object):
    """Runs the tools; with a cache directory, the oracle's results are
    kept on disk, keyed by the command line, the environment given, the
    content of every file argument and `salt` (the reference tools and
    the databases), so that a rerun only runs the Rust tools."""

    def __init__(self, cache_dir=None, salt=''):
        self.cache_dir = cache_dir
        self.salt = salt
        self.lock = threading.Lock()
        self.counts = {'oracle': 0, 'cached': 0, 'rust': 0}

    def count(self, what):
        with self.lock:
            self.counts[what] += 1

    def key(self, argv, env, outputs):
        h = hashlib.sha256()
        h.update(json.dumps([CACHE_FORMAT, self.salt, argv,
                             sorted((env or {}).items()),
                             list(outputs)]).encode())
        for arg in argv:
            path = arg.split('=', 1)[-1] if arg.startswith('--') else arg
            if path not in outputs and os.path.isfile(path):
                h.update(path.encode() + b'\0')
                with open(path, 'rb') as f:
                    for block in iter(lambda: f.read(1 << 20), b''):
                        h.update(block)
        return h.hexdigest()

    def run(self, argv, env=None, outputs=(), oracle=False, keep=()):
        """(exit code, stdout, stderr, {basename: bytes or None}) of the
        outputs, which are removed; a SIGABRT is exit code 134. The cache
        keeps stdout and the outputs larger than CACHE_KEEP_LIMIT
        compressed bytes as a Digest (which compares equal to the bytes
        it was made from), except the outputs named in `keep`."""
        path = None
        if oracle and self.cache_dir:
            path = os.path.join(self.cache_dir,
                                self.key(argv, env, outputs) + '.json')
            try:
                with open(path) as f:
                    data = json.load(f)
                self.count('cached')
                files = dict(
                    (k, unpack(v)) for k, v in data['files'].items())
                if all(not isinstance(files[os.path.basename(k)], Digest)
                       for k in keep):
                    return (data['code'], unpack(data['stdout']),
                            unpack(data['stderr']), files)
            except (OSError, ValueError, KeyError):
                pass
        full_env = dict(os.environ)
        full_env.update(env or {})
        result = subprocess.run(argv,
                                cwd=REPO_ROOT,
                                env=full_env,
                                stdin=subprocess.DEVNULL,
                                capture_output=True,
                                timeout=3600)
        self.count('oracle' if oracle else 'rust')
        code = result.returncode
        if code == -6:
            code = 134
        files = read_and_remove(outputs)
        if path is not None:
            os.makedirs(self.cache_dir, exist_ok=True)
            tmp = '%s.%d.%d.tmp' % (path, os.getpid(), threading.get_ident())
            packed = {}
            for k in outputs:
                name = os.path.basename(k)
                packed[name] = pack(files[name], k not in keep)
            with open(tmp, 'w') as f:
                json.dump(
                    {
                        'argv': argv,
                        'code': code,
                        'stdout': pack(result.stdout, True),
                        'stderr': pack(result.stderr),
                        'files': packed
                    }, f)
            os.replace(tmp, path)
        return code, result.stdout, result.stderr, files


class Digest(object):
    """The SHA-256 and size of a cached output: equal to bytes with that
    hash."""

    def __init__(self, sha, size):
        self.sha = sha
        self.size = size

    def __eq__(self, other):
        if isinstance(other, Digest):
            return self.sha == other.sha
        if isinstance(other, bytes):
            return hashlib.sha256(other).hexdigest() == self.sha
        return NotImplemented

    def __ne__(self, other):
        equal = self.__eq__(other)
        return equal if equal is NotImplemented else not equal

    def __len__(self):
        return self.size

    def __getitem__(self, index):
        return ('<cached output, sha256 %s, rerun with --no-result-cache '
                'to see it>' % self.sha).encode()

    def __repr__(self):
        return 'Digest(%r, %d)' % (self.sha, self.size)


def pack(data, digest=False):
    if data is None:
        return None
    text = base64.b64encode(zlib.compress(data, 6)).decode('ascii')
    if digest and len(text) > CACHE_KEEP_LIMIT:
        return {'sha256': hashlib.sha256(data).hexdigest(), 'size': len(data)}
    return text


def unpack(value):
    if value is None:
        return None
    if isinstance(value, dict):
        return Digest(value['sha256'], value['size'])
    return zlib.decompress(base64.b64decode(value))


PLAIN_RUNNER = Runner()


def run(runner, tool, args, out_path, env=None, oracle=False, keep=False):
    """fasm2frames: (exit code, stdout, stderr text, .frm bytes or None)."""
    code, out, err, files = runner.run([tool] + args + [out_path],
                                       env=env,
                                       outputs=[out_path],
                                       oracle=oracle,
                                       keep=[out_path] if keep else [])
    return (code, out, err.decode('utf-8', 'surrogateescape'),
            files[os.path.basename(out_path)])


def compare(case,
            oracle,
            rust,
            tmpdir,
            tools=None,
            runner=PLAIN_RUNNER,
            rust_env=None,
            bitstream=None,
            bitread_flags=None):
    """Runs one case, returns (ok, message, rules applied, bitstream tool
    runs). `rust_env`: extra environment of the Rust tool (e.g.
    FASM_XDB_CACHE=0); `bitstream`: whether the oracle's .frm also goes
    through the bitstream tools (default: the variants of
    BITSTREAM_VARIANTS), with `bitread_flags` (default BITREAD_FLAGS)."""
    name, fasm, db, part, flags = case
    args = ['--db-root', db, '--part', part] + flags + [fasm]
    tag = re.sub(r'[^\w.-]', '_', name)
    if bitstream is None:
        variant = name.rsplit('[', 1)[-1].rstrip(']')
        bitstream = variant in BITSTREAM_VARIANTS
    o = run(runner,
            oracle,
            args,
            os.path.join(tmpdir, tag + '.oracle.frm'),
            oracle=True,
            keep=bool(tools and bitstream))
    r = run(runner,
            rust,
            args,
            os.path.join(tmpdir, tag + '.rust.frm'),
            env=rust_env)
    rules = dict.fromkeys(RULES, 0)
    problems = []
    if o[0] != r[0]:
        problems.append('exit code %d (oracle) != %d (rust)' % (o[0], r[0]))
    if o[3] != r[3]:
        problems.append('.frm output differs (%s vs %s bytes)' %
                        (None if o[3] is None else len(o[3]),
                         None if r[3] is None else len(r[3])))
    if o[1] != r[1]:
        problems.append('stdout differs')
    o_err = o[2]
    if 'Traceback (most recent call last):' in o_err:
        rules['1-traceback'] += 1
        o_err = strip_traceback(o_err)
    o_type, _ = exception_type(o_err)
    if (CTYPES_MARKER in o_err and o_err.rstrip('\n').endswith(NONE_TYPE)
            and PARSE_ERROR_RE.match(r[2])):
        # Rule 4: ANTLR value range error.
        rules['4-value-range'] += 1
        if o[0] != 1 or r[0] != 1:
            problems.append('value range error: expected exit code 1')
    elif (o_type is not None and o_type not in EXACT_EXCEPTIONS
          and r[2].startswith('fasm_xilinx.DbError: ')):
        # Rule 3: database errors.
        rules['3-db-error'] += 1
        if o[0] != 1 or r[0] != 1:
            problems.append('database error: expected exit code 1')
    elif normalise(o_err, rules) != normalise(r[2], dict.fromkeys(RULES, 0)):
        problems.append('stderr differs:\n--- oracle\n%s--- rust\n%s' %
                        (o_err[:4000], r[2][:4000]))
    bitstream_runs = 0
    part_file = os.path.join(db, part, 'part.yaml')
    if (tools and not problems and o[0] == 0 and bitstream
            and os.path.exists(part_file)):
        frm = os.path.join(tmpdir, tag + '.oracle.bitstream.frm')
        with open(frm, 'wb') as f:
            f.write(o[3])
        more, bitstream_runs = compare_bitstream(frm, part_file, part, tools,
                                                 tmpdir, tag, runner,
                                                 bitread_flags)
        problems += more
        os.remove(frm)
    return (not problems, '%s: %s' % (name, '; '.join(problems)), rules,
            bitstream_runs)


def bit_time(data):
    """The seconds since the epoch of a .bit header's date and time, or
    None."""
    if data is None:
        return None
    m = re.search(
        rb'c\x00\x0b(\d{4})/(\d\d)/(\d\d)\x00d\x00\x09'
        rb'(\d\d):(\d\d):(\d\d)\x00', data[:4096])
    if not m:
        return None
    return calendar.timegm(tuple(int(g) for g in m.groups()))


def run_tool(argv, env=None, runner=PLAIN_RUNNER, oracle=False):
    """(exit code, stdout, stderr); a SIGABRT is exit code 134."""
    return runner.run(argv, env=env, oracle=oracle)[:3]


def read_and_remove(paths):
    out = {}
    for path in paths:
        try:
            with open(path, 'rb') as f:
                out[os.path.basename(path)] = f.read()
            os.remove(path)
        except OSError:
            out[os.path.basename(path)] = None
    return out


def normalise_gflags_paths(data, tool):
    """The reference prints its own path (`argv[0]`); both become PROG."""
    return re.sub(rb"/[^\s:']*/" + tool.encode() + rb'\b', b'PROG', data)


def compare_runs(what, o, r):
    """Problems between (code, stdout, stderr, files) of the oracle and
    of the Rust tool."""
    problems = []
    for i, name in enumerate(('exit code', 'stdout', 'stderr')):
        if o[i] != r[i]:
            problems.append('%s: %s differs:\n--- oracle\n%r\n--- rust\n%r' %
                            (what, name, o[i][:2000], r[i][:2000]))
    for name in sorted(set(o[3]) | set(r[3])):
        a, b = o[3].get(name), r[3].get(name)
        if a != b:
            first = None
            if (a is not None and b is not None
                    and not isinstance(a, Digest)):
                first = next((i for i in range(min(len(a), len(b)))
                              if a[i] != b[i]), min(len(a), len(b)))
            problems.append('%s: file %s differs (%s vs %s bytes, first '
                            'difference at %s)' %
                            (what, name, None if a is None else len(a),
                             None if b is None else len(b), first))
    return problems


def run_bitread(tools,
                part_file,
                bit,
                flags,
                tmpdir,
                tag,
                runner=PLAIN_RUNNER):
    """Runs both bitreads with `flags` on `bit`; returns the problems."""
    results = []
    for side in ('oracle', 'rust'):
        args = list(flags)
        files = []
        for option in ('-o', '--aux'):
            if option in args:
                path = os.path.join(tmpdir,
                                    '%s.%s.txt' % (tag, option.strip('-')))
                args.insert(args.index(option) + 1, path)
                files.append(path)
        argv = [tools[side + '_bitread'], '--part_file=' + part_file]
        code, out, err, outputs = runner.run(
            argv + args + [bit],
            outputs=files,
            oracle=side == 'oracle')
        if not isinstance(out, Digest) and not isinstance(
                results[0][1] if results else None, Digest):
            # (A cached large output has no path to normalise.)
            out = normalise_gflags_paths(out, 'bitread')
        results.append((code, out, err, outputs))
    return compare_runs('bitread %s' % ' '.join(flags), *results)


def compare_bitstream(frm,
                      part_file,
                      part,
                      tools,
                      tmpdir,
                      tag,
                      runner=PLAIN_RUNNER,
                      bitread_flags=None):
    """xc7frames2bit on the oracle's .frm, then bitread on the .bit;
    returns (problems, runs)."""
    if bitread_flags is None:
        bitread_flags = BITREAD_FLAGS
    bit = os.path.join(tmpdir, tag + '.bit')
    base = [
        '--frm_file=' + frm, '--output_file=' + bit, '--part_name=' + part,
        '--part_file=' + part_file
    ]
    o = runner.run([tools['oracle_frames2bit']] + base,
                   outputs=[bit],
                   oracle=True,
                   keep=[bit])
    data = o[3][tag + '.bit']
    epoch = bit_time(data)
    env = {'SOURCE_DATE_EPOCH': str(epoch)} if epoch is not None else {}
    r = runner.run([tools['rust_frames2bit']] + base, env=env, outputs=[bit])
    problems = compare_runs('xc7frames2bit', o, r)
    if problems or o[0] != 0 or data is None:
        return problems, 1
    with open(bit, 'wb') as f:
        f.write(data)
    for i, flags in enumerate(bitread_flags):
        problems += run_bitread(tools, part_file, bit, flags, tmpdir,
                                '%s.%d' % (tag, i), runner)
    os.remove(bit)
    return problems, 1 + len(bitread_flags)


def compare_xcfasm(case, tools, tmpdir, runner=PLAIN_RUNNER, rust_env=None):
    """xcfasm-oracle vs the Rust xcfasm; (ok, message, rules applied)."""
    name, fasm, db, part, flags = case
    part_file = os.path.join(db, part, 'part.yaml')
    tag = re.sub(r'[^\w.-]', '_', name)
    frm = os.path.join(tmpdir, tag + '.xcfasm.frm')
    bit = os.path.join(tmpdir, tag + '.xcfasm.bit')
    args = [
        '--db-root', db, '--part', part, '--part_file', part_file,
        '--frm2bit', tools['oracle_frames2bit'], '--fn_in', fasm,
        '--frm_out', frm, '--bit_out', bit
    ] + flags
    # The wrapper warns when no xc7frames2bit is on PATH (the tool itself
    # is given with --frm2bit): put the reference binaries there.
    bin_dir = os.path.join(
        os.path.dirname(os.path.abspath(tools['oracle_xcfasm'])), 'build',
        'xilinx', 'bin')
    o = runner.run([tools['oracle_xcfasm']] + args,
                   env={'PATH': bin_dir + os.pathsep + os.environ['PATH']},
                   outputs=[frm, bit],
                   oracle=True,
                   keep=[bit])
    epoch = bit_time(o[3][os.path.basename(bit)])
    env = dict(rust_env or {})
    if epoch is not None:
        env['SOURCE_DATE_EPOCH'] = str(epoch)
    r = runner.run([tools['rust_xcfasm']] + args, env=env, outputs=[frm, bit])
    o_full = o[2].decode('utf-8', 'surrogateescape')
    o_err = strip_traceback(o_full)
    r_err = r[2].decode('utf-8', 'surrogateescape')
    rules = dict.fromkeys(RULES, 0)
    if o_err != o_full:
        rules['1-traceback'] += 1
    o_type, _ = exception_type(o_err)
    if (CTYPES_MARKER in o_err and o_err.rstrip('\n').endswith(NONE_TYPE)
            and PARSE_ERROR_RE.match(r_err)):
        rules['4-value-range'] += 1
        o_err = r_err = '<value range error>'
    elif (o_type is not None and o_type not in EXACT_EXCEPTIONS
          and o_type != 'subprocess.CalledProcessError'
          and r_err.startswith('fasm_xilinx.DbError: ')):
        rules['3-db-error'] += 1
        o_err = r_err = '<database error>'
    else:
        o_err = normalise(o_err, rules)
        r_err = normalise(r_err, dict.fromkeys(RULES, 0))
    problems = compare_runs('xcfasm', (o[0], o[1], o_err.encode(), o[3]),
                            (r[0], r[1], r_err.encode(), r[3]))
    return not problems, '%s: %s' % (name, '; '.join(problems)), rules


def reference_bitstreams(bitread_oracle, db_cache, tmpdir):
    """(name, part_file, bit) of the reference bitstreams that exist."""
    out = []
    db = os.path.join(db_cache, 'prjxray-db', 'artix7')
    smoke = os.path.join(REPO_ROOT, 'tests', 'corpus', 'xilinx', 'artix7',
                         'smoke_x1y0.bit')
    if os.path.isdir(db):
        out.append(('smoke_x1y0.bit',
                    os.path.join(db, FAMILY_PARTS['artix7'],
                                 'part.yaml'), smoke))
    test_data = os.path.join(os.path.dirname(os.path.abspath(bitread_oracle)),
                             'build', 'xilinx', 'src', 'prjxray', 'lib',
                             'test_data')
    if os.path.isdir(test_data):
        yaml = os.path.join(test_data, 'configuration_test.yaml')
        for f in ('configuration_test.bit', 'configuration_test.debug.bit',
                  'configuration_test.perframecrc.bit'):
            out.append((f, yaml, os.path.join(test_data, f)))
        tools = os.path.join(test_data, 'ToolsTestData.tar.gz')
        if os.path.exists(tools):
            with tarfile.open(tools) as tar:
                for member in ('Series7/part.yaml', 'Series7/design.bit',
                               'Series7/bram.bit'):
                    tar.extract(member, tmpdir)
            s7 = os.path.join(tmpdir, 'Series7')
            for f in ('design.bit', 'bram.bit'):
                out.append(('ToolsTestData/Series7/' + f,
                            os.path.join(s7, 'part.yaml'),
                            os.path.join(s7, f)))
    return out


def compare_reference_bit(item, tools, tmpdir, runner=PLAIN_RUNNER):
    name, part_file, bit = item
    tag = re.sub(r'[^\w.-]', '_', name)
    problems = []
    for i, flags in enumerate(BITREAD_FLAGS):
        problems += run_bitread(tools, part_file, bit, flags, tmpdir,
                                '%s.%d' % (tag, i), runner)
    return not problems, '%s: %s' % (name, '; '.join(problems))


def corpus(db_cache, pattern):
    """The (name, fasm, db, part, flags) cases and skipped notes."""
    cases = []
    notes = []
    sources = []
    xilinx = os.path.join(REPO_ROOT, 'tests', 'corpus', 'xilinx')
    for family in sorted(os.listdir(xilinx)):
        if not os.path.isdir(os.path.join(xilinx, family)):
            continue
        db = os.path.join(db_cache, 'prjxray-db', family)
        part = FAMILY_PARTS.get(family)
        if part is None:
            notes.append('no part for family %s' % family)
            continue
        if not os.path.isdir(db):
            notes.append('skipping %s: %s not found (tools/fetch-db.sh '
                         'prjxray %s)' % (family, db, family))
            continue
        sources.append((os.path.join(xilinx, family), db, part))
    sources.append((os.path.join(REPO_ROOT, 'tests', 'corpus',
                                 'f4pga-xc-fasm'), MINI_DB, 'xc7'))
    for root, db, part in sources:
        for dirpath, _, files in sorted(os.walk(root)):
            for f in sorted(files):
                if not f.endswith('.fasm'):
                    continue
                fasm = os.path.join(dirpath, f)
                rel = os.path.relpath(fasm, REPO_ROOT)
                if pattern and not fnmatch.fnmatch(rel, pattern):
                    continue
                variants = list(VARIANTS)
                roi = fasm[:-len('.fasm')] + '.roi.json'
                if os.path.exists(roi):
                    variants.append(('roi', ['--sparse', '--roi', roi]))
                for vname, flags in variants:
                    cases.append(('%s[%s]' % (rel, vname), rel, db, part,
                                  flags))
    return cases, notes


# ---------------------------------------------------------------------
# All parts of a family (T5.9): a generated corpus per part.
# ---------------------------------------------------------------------
GENERATOR = os.path.join(REPO_ROOT, 'tools', 'gen-xilinx-corpus.py')
FETCH_DB = os.path.join(REPO_ROOT, 'tools', 'fetch-db.sh')
PRJXRAY_FAMILIES = ('artix7', 'kintex7', 'spartan7', 'zynq7')
# Free space wanted before fetching a family (each is 180-250 MiB checked
# out, plus the git objects).
FETCH_MIN_FREE = 1 << 30
EXPLAINED_RULES = ('3-db-error', '4-value-range')


def file_sha256(path):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for block in iter(lambda: f.read(1 << 20), b''):
            h.update(block)
    return h.hexdigest()


def find_family(db_dirs, family):
    for d in db_dirs:
        path = os.path.join(d, 'prjxray-db', family)
        if os.path.isdir(os.path.join(path, 'mapping')):
            return path
    return None


def fetch_family(db_dirs, family):
    """tools/fetch-db.sh prjxray FAMILY into the first database directory,
    if there is room; returns the family directory or None."""
    target = db_dirs[0]
    os.makedirs(target, exist_ok=True)
    free = shutil.disk_usage(target).free
    print('difftest-xilinx: %s has %.1f GiB free' % (target, free / 2.0**30))
    if free < FETCH_MIN_FREE:
        print('difftest-xilinx: not fetching %s: less than %.1f GiB free' %
              (family, FETCH_MIN_FREE / 2.0**30))
        return None
    env = dict(os.environ)
    env['FASM_DB_CACHE'] = target
    result = subprocess.run([FETCH_DB, 'prjxray', family], env=env)
    if result.returncode != 0:
        print('difftest-xilinx: fetching %s failed' % family)
        return None
    return find_family([target], family)


def db_commit(family_dir):
    """The commit of the prjxray-db checkout (or 'unknown')."""
    try:
        with open(os.path.join(os.path.dirname(family_dir), '.git',
                               'HEAD')) as f:
            return f.read().strip()
    except OSError:
        return 'unknown'


def oracle_identity(paths):
    """Identifies the reference tools: the wrappers' content, the size and
    modification time of the binaries they run and of the Python packages
    of the oracle venv."""
    h = hashlib.sha256()
    for path in paths:
        if path is None:
            continue
        if os.path.isfile(path):
            h.update(file_sha256(path).encode())
        oracle_dir = os.path.dirname(os.path.abspath(path))
        for sub in ('build/xilinx/bin', 'venv-xilinx/lib'):
            top = os.path.join(oracle_dir, sub)
            for dirpath, dirnames, files in os.walk(top):
                dirnames[:] = sorted(d for d in dirnames
                                     if d not in ('__pycache__', 'tests'))
                if sub.endswith('lib') and not any(
                        p in dirpath for p in ('/prjxray', '/xc_fasm',
                                               '/fasm')):
                    continue
                for f in sorted(files):
                    if f.endswith('.pyc'):
                        continue
                    st = os.stat(os.path.join(dirpath, f))
                    h.update(('%s %d %d\n' % (os.path.join(dirpath, f),
                                              st.st_size,
                                              st.st_mtime_ns)).encode())
    return h.hexdigest()


def generator_options(args):
    return [
        '--tiles',
    ] + args.tiles + [
        '--seed',
        str(args.seed), '--density',
        str(args.density), '--max-per-tile',
        str(args.max_per_tile)
    ]


def generate(db, part, options, corpus_dir, commit):
    """Generates the corpus of a part unless the manifest of the same
    generator, options and database is there; returns the manifest."""
    key = hashlib.sha256(
        json.dumps([file_sha256(GENERATOR), options, commit,
                    db]).encode()).hexdigest()
    manifest = os.path.join(corpus_dir, 'manifest.json')
    stamp = os.path.join(corpus_dir, 'key')
    try:
        with open(stamp) as f:
            if f.read().strip() == key:
                with open(manifest) as m:
                    return json.load(m)
    except (OSError, ValueError):
        pass
    argv = [
        sys.executable, GENERATOR, '--db-root', db, '--part', part,
        '--out-dir', corpus_dir
    ]
    result = subprocess.run(argv + options, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError('gen-xilinx-corpus.py failed for %s:\n%s' %
                           (part, result.stderr))
    with open(stamp, 'w') as f:
        f.write(key + '\n')
    with open(manifest) as m:
        return json.load(m)


def part_cases(corpus_dir, manifest, db, part):
    """[(case, options)] of a part: the first features file with every
    VARIANTS flag set (dense, sparse and pudc also through the bitstream
    tools), once more sparse without the Rust database cache
    (FASM_XDB_CACHE=0), the other features files and the error files
    sparse (the others through xc7frames2bit and the first two bitread
    flag sets)."""
    out = []
    name = manifest['files'][0]
    first = os.path.join(corpus_dir, name)
    for vname, flags in VARIANTS:
        case = ('%s[%s]' % (name, vname), first, db, part, flags)
        out.append((case, {'bitstream': vname in BITSTREAM_VARIANTS}))
    case = (name + '[sparse,FASM_XDB_CACHE=0]', first, db, part, ['--sparse'])
    out.append((case, {
        'bitstream': False,
        'rust_env': {
            'FASM_XDB_CACHE': '0'
        }
    }))
    for name in manifest['files'][1:]:
        case = (name + '[sparse]', os.path.join(corpus_dir, name), db, part,
                ['--sparse'])
        out.append((case, {
            'bitstream': True,
            'bitread_flags': BITREAD_FLAGS[:2]
        }))
    for name in manifest['errors']:
        case = ('errors/%s[sparse]' % name,
                os.path.join(corpus_dir, 'errors', name), db, part,
                ['--sparse'])
        out.append((case, {'bitstream': False}))
    return out


def run_part(family, db, part, args, tools, runner, commit):
    """Generates the corpus of one part and compares every run; returns
    the part's result row."""
    start = time.time()
    options = generator_options(args)
    slug = re.sub(r'[^\w.-]', '_',
                  '-'.join(args.tiles) + '-s' + str(args.seed))
    corpus_dir = os.path.join(args.work_dir, 'corpus', family, part, slug)
    row = {
        'family': family,
        'part': part,
        'fabric': '',
        'lines': 0,
        'files': 0,
        'fasm2frames': [0, 0, 0, 0],  # runs, identical, explained, different
        'bitstream': 0,
        'xcfasm': [0, 0, 0, 0],
        'failures': [],
        'rules': dict.fromkeys(RULES, 0),
    }
    try:
        manifest = generate(db, part, options, corpus_dir, commit)
    except RuntimeError as e:
        row['failures'].append(str(e))
        row['seconds'] = time.time() - start
        return row
    row['fabric'] = manifest['fabric']
    row['lines'] = manifest['lines']
    row['files'] = len(manifest['files']) + len(manifest['errors'])
    run_dir = os.path.join(args.work_dir, 'run', family, part)
    shutil.rmtree(run_dir, ignore_errors=True)
    os.makedirs(run_dir)
    xdb = None
    rust_env_base = {}
    if args.xdb_cache != '0':
        xdb = os.path.join(args.xdb_cache or run_dir, 'xdb')
        rust_env_base['FASM_XDB_CACHE'] = xdb

    def tally(counts, ok, rules):
        counts[0] += 1
        explained = any(rules.get(r) for r in EXPLAINED_RULES)
        if not ok:
            counts[3] += 1
        elif explained:
            counts[2] += 1
        else:
            counts[1] += 1
        for k, v in rules.items():
            row['rules'][k] += v

    for case, opts in part_cases(corpus_dir, manifest, db, part):
        rust_env = dict(rust_env_base)
        rust_env.update(opts.get('rust_env', {}))
        ok, message, rules, runs = compare(
            case,
            args.oracle,
            args.rust,
            run_dir,
            tools,
            runner,
            rust_env=rust_env,
            bitstream=opts.get('bitstream'),
            bitread_flags=opts.get('bitread_flags'))
        tally(row['fasm2frames'], ok, rules)
        row['bitstream'] += runs
        if not ok:
            row['failures'].append('%s %s' % (part, message))
    if tools and os.path.exists(os.path.join(db, part, 'part.yaml')):
        first = os.path.join(corpus_dir, manifest['files'][0])
        for vname, vflags in XCFASM_VARIANTS:
            case = ('%s[xcfasm-%s]' % (manifest['files'][0], vname), first, db,
                    part, vflags)
            ok, message, rules = compare_xcfasm(case, tools, run_dir, runner,
                                                rust_env_base)
            tally(row['xcfasm'], ok, rules)
            if not ok:
                row['failures'].append('%s %s' % (part, message))
    if not args.keep_run_dir:
        shutil.rmtree(run_dir, ignore_errors=True)
    row['seconds'] = time.time() - start
    return row


def print_table(rows):
    header = ('part', 'fabric', 'lines', 'files', 'fasm2frames i/e/d',
              'bit+bitread', 'xcfasm i/e/d', 'seconds')
    table = [header]
    for r in rows:
        f, x = r['fasm2frames'], r['xcfasm']
        table.append((r['part'], r['fabric'], str(r['lines']), str(r['files']),
                      '%d/%d/%d' % (f[1], f[2], f[3]), str(r['bitstream']),
                      '%d/%d/%d' % (x[1], x[2], x[3]),
                      '%.0f' % r['seconds']))
    widths = [max(len(row[i]) for row in table) for i in range(len(header))]
    for i, row in enumerate(table):
        print('  '.join(c.ljust(w) for c, w in zip(row, widths)).rstrip())
        if i == 0:
            print('  '.join('-' * w for w in widths))


def families_main(args, tools):
    """--family/--families: every (or --parts GLOB) part of the families,
    generated corpus; per part table and totals."""
    families = []
    for item in args.families:
        families += [f for f in item.split(',') if f]
    db_dirs = args.db_cache.split(os.pathsep)
    selected = []
    for family in families:
        if family not in PRJXRAY_FAMILIES:
            print('difftest-xilinx: unknown family %s (known: %s)' %
                  (family, ', '.join(PRJXRAY_FAMILIES)),
                  file=sys.stderr)
            return EXIT_NOT_SET_UP
        db = find_family(db_dirs, family)
        if db is None and not args.no_fetch:
            db = fetch_family(db_dirs, family)
        if db is None:
            print('difftest-xilinx: database of %s not found in %s' %
                  (family, args.db_cache),
                  file=sys.stderr)
            return EXIT_NOT_SET_UP
        parts = subprocess.run(
            [sys.executable, GENERATOR, '--db-root', db, '--list-parts'],
            capture_output=True,
            text=True,
            check=True).stdout.split()
        if args.parts:
            globs = args.parts.split(',')
            parts = [
                p for p in parts if any(fnmatch.fnmatch(p, g) for g in globs)
            ]
        elif not args.all_parts:
            parts = parts[:1]
        selected += [(family, db, p) for p in parts]
    if args.list:
        for family, db, part in selected:
            print('%s %s' % (family, part))
        return EXIT_OK
    commits = dict((db, db_commit(db)) for _, db, _ in selected)
    salt = json.dumps([
        oracle_identity([
            args.oracle, args.frames2bit_oracle, args.bitread_oracle,
            args.xcfasm_oracle
        ]),
        sorted(commits.items())
    ])
    cache_dir = None
    if not args.no_result_cache:
        cache_dir = os.path.join(args.work_dir, 'results')
    runner = Runner(cache_dir, salt)
    start = time.time()
    print('difftest-xilinx: %d parts of %s, corpus --tiles %s --seed %s, '
          '%d jobs, work directory %s' %
          (len(selected), ', '.join(families), ' '.join(
              args.tiles), args.seed, args.jobs, args.work_dir))
    rows = []
    with concurrent.futures.ThreadPoolExecutor(args.jobs) as pool:
        futures = [
            pool.submit(run_part, family, db, part, args, tools, runner,
                        commits[db]) for family, db, part in selected
        ]
        for future in concurrent.futures.as_completed(futures):
            row = future.result()
            rows.append(row)
            f = row['fasm2frames']
            print('%-4s %-22s %6d lines %3d files  fasm2frames %d/%d/%d  '
                  'xcfasm %d/%d/%d  %.0f s' %
                  ('FAIL' if row['failures'] else 'ok', row['part'],
                   row['lines'], row['files'], f[1], f[2], f[3],
                   row['xcfasm'][1], row['xcfasm'][2], row['xcfasm'][3],
                   row['seconds']),
                  flush=True)
            for failure in row['failures']:
                print('  FAIL %s' % failure)
    order = dict(((f, p), i) for i, (f, _, p) in enumerate(selected))
    rows.sort(key=lambda r: order[(r['family'], r['part'])])
    print()
    print_table(rows)
    totals = [0] * 4
    xtotals = [0] * 4
    rules = dict.fromkeys(RULES, 0)
    for r in rows:
        for i in range(4):
            totals[i] += r['fasm2frames'][i]
            xtotals[i] += r['xcfasm'][i]
        for k, v in r['rules'].items():
            rules[k] += v
    wall = time.time() - start
    print()
    print('difftest-xilinx: %d parts, %d FASM files, %d lines; fasm2frames '
          '%d runs: %d identical, %d explained, %d different; '
          'xc7frames2bit + bitread %d runs; xcfasm %d runs: %d identical, '
          '%d explained, %d different' %
          (len(rows), sum(r['files'] for r in rows), sum(
              r['lines'] for r in rows), totals[0], totals[1], totals[2],
           totals[3], sum(r['bitstream'] for r in rows), xtotals[0],
           xtotals[1], xtotals[2], xtotals[3]))
    for rule, count in sorted(rules.items()):
        print('  normalisation rule %s: applied %d time(s)' % (rule, count))
    print('difftest-xilinx: oracle runs %d (%d from the result cache), Rust '
          'runs %d, wall time %.0f s' %
          (runner.counts['oracle'] + runner.counts['cached'],
           runner.counts['cached'], runner.counts['rust'], wall))
    if args.json_report:
        with open(args.json_report, 'w') as f:
            json.dump({'rows': rows, 'wall_seconds': wall}, f, indent=1)
    failed = any(r['failures'] for r in rows)
    return EXIT_DIFFERENCES if failed else EXIT_OK


def main():
    parser = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    parser.add_argument('--oracle',
                        default=os.environ.get('FASM2FRAMES_ORACLE',
                                               DEFAULT_ORACLE),
                        help='reference fasm2frames (default: %(default)s)')
    parser.add_argument('--rust',
                        default=os.environ.get('FASM2FRAMES_RUST',
                                               DEFAULT_RUST),
                        help='Rust fasm2frames (default: %(default)s)')
    oracle_dir = os.path.join(REPO_ROOT, 'tests', 'oracle')
    parser.add_argument(
        '--frames2bit-oracle',
        default=os.environ.get('XC7FRAMES2BIT_ORACLE',
                               os.path.join(oracle_dir,
                                            'xc7frames2bit-oracle')),
        help='reference xc7frames2bit (default: %(default)s)')
    parser.add_argument('--bitread-oracle',
                        default=os.environ.get(
                            'BITREAD_ORACLE',
                            os.path.join(oracle_dir, 'bitread-oracle')),
                        help='reference bitread (default: %(default)s)')
    parser.add_argument('--xcfasm-oracle',
                        default=os.environ.get(
                            'XCFASM_ORACLE',
                            os.path.join(oracle_dir, 'xcfasm-oracle')),
                        help='reference xcfasm (default: %(default)s)')
    parser.add_argument('--rust-dir',
                        default=os.environ.get('FASM_RUST_DIR',
                                               DEFAULT_RUST_DIR),
                        help='directory of the Rust xc7frames2bit, bitread '
                        'and xcfasm (default: %(default)s)')
    parser.add_argument('--no-bitstream',
                        action='store_true',
                        help='only compare fasm2frames')
    parser.add_argument('--db-cache',
                        default=DEFAULT_DB_CACHE,
                        help='directory of fetched databases, or several '
                        'separated by "%s" (searched in order; a family is '
                        'fetched into the first) (default: $FASM_DB_CACHE '
                        'or %%(default)s)' % os.pathsep)
    parser.add_argument('--filter', help='only FASM files matching GLOB')
    parser.add_argument('--jobs', type=int, default=os.cpu_count() or 1)
    parser.add_argument('-v', '--verbose', action='store_true')
    group = parser.add_argument_group(
        'all parts of a family (generated corpus, tools/gen-xilinx-corpus.py)')
    group.add_argument('--family',
                       '--families',
                       dest='families',
                       action='append',
                       default=[],
                       metavar='F[,F...]',
                       help='prjxray-db families (%s); a family not found '
                       'in --db-cache is fetched with tools/fetch-db.sh' %
                       ', '.join(PRJXRAY_FAMILIES))
    group.add_argument('--all-parts',
                       action='store_true',
                       help='every part of mapping/parts.yaml (default: '
                       'the first)')
    group.add_argument('--parts',
                       metavar='GLOB[,GLOB...]',
                       help='the parts matching these globs')
    group.add_argument('--list',
                       action='store_true',
                       help='print the selected parts and exit')
    group.add_argument('--no-fetch',
                       action='store_true',
                       help='do not fetch missing families')
    group.add_argument('--tiles',
                       nargs='+',
                       default=['sample', '3'],
                       metavar='MODE',
                       help='generator --tiles: first | sample N | all '
                       '(default: sample 3)')
    group.add_argument('--seed', default='0', help='generator --seed')
    group.add_argument('--density',
                       default='0.5',
                       help='generator --density (default %(default)s)')
    group.add_argument('--max-per-tile',
                       default='0',
                       help='generator --max-per-tile (default: no bound)')
    group.add_argument('--work-dir',
                       default=os.environ.get('FASM_DIFFTEST_XILINX_WORK',
                                              DEFAULT_WORK_DIR),
                       help='generated corpora, oracle result cache and run '
                       'directories (default: $FASM_DIFFTEST_XILINX_WORK '
                       'or %(default)s)')
    group.add_argument('--no-result-cache',
                       action='store_true',
                       help='always run the reference tools')
    group.add_argument('--xdb-cache',
                       help='FASM_XDB_CACHE of the Rust tools (default: a '
                       'directory per part, removed with its run '
                       'directory; 0: no cache)')
    group.add_argument('--keep-run-dir',
                       action='store_true',
                       help='keep the run directories (outputs, xdb cache)')
    group.add_argument('--json-report', help='write the result rows here')
    args = parser.parse_args()

    # The Rust tools' binary database cache (FASM_XDB_CACHE, see
    # docs/rewrite/DESIGN-xilinx-db.md §8.8): a temporary directory of
    # this run unless set, so that the cached path is covered (written by
    # the first runs, loaded by the others) without writing into ~/.cache.
    if 'FASM_XDB_CACHE' not in os.environ:
        cache_dir = tempfile.mkdtemp(prefix='fasm-xdb-cache-')
        atexit.register(shutil.rmtree, cache_dir, True)
        os.environ['FASM_XDB_CACHE'] = cache_dir

    for tool in (args.oracle, args.rust):
        if not os.access(tool, os.X_OK):
            print('difftest-xilinx: %s not found' % tool, file=sys.stderr)
            return EXIT_NOT_SET_UP
    tools = None
    if not args.no_bitstream:
        tools = {
            'oracle_frames2bit': args.frames2bit_oracle,
            'oracle_bitread': args.bitread_oracle,
            'oracle_xcfasm': args.xcfasm_oracle,
            'rust_frames2bit': os.path.join(args.rust_dir, 'xc7frames2bit'),
            'rust_bitread': os.path.join(args.rust_dir, 'bitread'),
            'rust_xcfasm': os.path.join(args.rust_dir, 'xcfasm'),
        }
        rust_missing = [
            t for k, t in tools.items()
            if k.startswith('rust') and not os.access(t, os.X_OK)
        ]
        if rust_missing:
            print('difftest-xilinx: %s not found' % ', '.join(rust_missing),
                  file=sys.stderr)
            return EXIT_NOT_SET_UP
        # The oracle wrappers exist in the source tree; the binaries they
        # run only after tests/oracle/setup-xilinx.sh.
        probe = run_tool([tools['oracle_frames2bit'], '--version'])
        if probe[0] != 0:
            print('skipping the bitstream tools: %s does not run '
                  '(tests/oracle/setup-xilinx.sh)' %
                  tools['oracle_frames2bit'])
            tools = None
            args.frames2bit_oracle = args.bitread_oracle = None
            args.xcfasm_oracle = None

    if args.families:
        return families_main(args, tools)

    cases, notes = corpus(args.db_cache.split(os.pathsep)[0], args.filter)
    for note in notes:
        print(note)
    totals = dict.fromkeys(RULES, 0)
    failures = []
    files = set(case[1] for case in cases)
    bitstream_runs = 0
    xcfasm_cases = []
    if tools:
        seen = set()
        for name, fasm, db, part, flags in cases:
            key = (fasm, db, part)
            if key in seen or not os.path.exists(
                    os.path.join(db, part, 'part.yaml')):
                continue
            seen.add(key)
            variants = list(XCFASM_VARIANTS)
            roi = os.path.join(REPO_ROOT, fasm)[:-len('.fasm')] + '.roi.json'
            if os.path.exists(roi):
                variants.append(('roi', ['--sparse', '--roi', roi]))
            for vname, vflags in variants:
                xcfasm_cases.append(('%s[xcfasm-%s]' % (fasm, vname), fasm,
                                     db, part, vflags))
    xcfasm_failures = []
    bit_failures = []
    with tempfile.TemporaryDirectory(prefix='difftest-xilinx-') as tmpdir:
        references = []
        if tools and not args.filter:
            references = reference_bitstreams(args.bitread_oracle,
                                              args.db_cache, tmpdir)
        with concurrent.futures.ThreadPoolExecutor(args.jobs) as pool:
            results = pool.map(
                lambda c: compare(c, args.oracle, args.rust, tmpdir, tools),
                cases)
            for (ok, message, rules, runs), case in zip(results, cases):
                bitstream_runs += runs
                for k, v in rules.items():
                    totals[k] += v
                if ok:
                    if args.verbose:
                        print('ok   %s' % case[0])
                else:
                    failures.append(message)
                    print('FAIL %s' % message)
            for (ok, message, _), case in zip(
                    pool.map(lambda c: compare_xcfasm(c, tools, tmpdir),
                             xcfasm_cases), xcfasm_cases):
                if ok:
                    if args.verbose:
                        print('ok   %s' % case[0])
                else:
                    xcfasm_failures.append(message)
                    print('FAIL %s' % message)
            for (ok, message), item in zip(
                    pool.map(lambda b: compare_reference_bit(b, tools, tmpdir),
                             references), references):
                if ok:
                    if args.verbose:
                        print('ok   bitread %s' % item[0])
                else:
                    bit_failures.append(message)
                    print('FAIL bitread %s' % message)
    print('difftest-xilinx: %d FASM files, %d runs, %d identical, %d '
          'different' % (len(files), len(cases), len(cases) - len(failures),
                         len(failures)))
    for rule, count in sorted(totals.items()):
        print('  normalisation rule %s: applied %d time(s)' % (rule, count))
    if tools:
        print('  xc7frames2bit + bitread runs on the oracle .frm files of '
              'these cases: %d (differences are counted in the cases above)' %
              bitstream_runs)
        print('difftest-xilinx: xcfasm: %d runs, %d identical, %d different' %
              (len(xcfasm_cases), len(xcfasm_cases) - len(xcfasm_failures),
               len(xcfasm_failures)))
        print('difftest-xilinx: bitread on %d reference bitstreams x %d flag '
              'sets: %d identical, %d different' %
              (len(references), len(BITREAD_FLAGS),
               len(references) - len(bit_failures), len(bit_failures)))
    any_failure = failures or xcfasm_failures or bit_failures
    return EXIT_DIFFERENCES if any_failure else EXIT_OK


if __name__ == '__main__':
    sys.exit(main())
